client/stringify.js
test/client/stringify.spec.js

Stringify uses the name of the constructor to serialize objects.
When the object was created using Object.create(null) or has a property
constructor this may throw an Error

fix(client): Fix stringify serializing objects

---

static/debug.html

Shielding a reference to `window.console.log`. Fixes the ability to use this page in IE without the inspector open. Fixes #1209.

Safeguard IE against console.log

---

docs/plus/01-requirejs.md
requirejs.config.tpl.coffee
requirejs.config.tpl.js

The `pathToModule` function sets a project up such that your spec
directory must be within your src directory. This approach directly
contradicts the example describing how to use RequireJS with Karma in
the documentation.
Fixes #1120, fixes #896

fix(init): fix test-main.(js/coffee) generation

---

lib/reporter.js
test/unit/reporter.spec.coffee

The symptom of this issue is that the test runner will die with the following error:
Fatal error: Line must be greater than or equal to 1, got 0
The way the error happened:
1) One of my specs was failing when calling getComputedStyle(). In Firefox this resulted in an error message with some weird formatting: "TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element. in http://172.20.132.80:8080/base/app/SilverApp/services/DragAvatarProducer.js?dc125e476a15c0e2f62b00901b3d0c1b6c407af8 (line 85)". The problem with that string is the line number is formatted "(line 85)" when it should be like ":85:7". This might be a bug against Firefox.
2) Karma's source-map support tried to parse the line & column, but couldn't because the formatting was weird. (see: …

fix: catch exceptions from SourceMapConsumer

---

lib/config.js
test/unit/config.spec.coffee

fix(config): Default remaining client options if any are set

---

client/main.js

Look up location.protocol for socket.io,
in order to use Karma in https-only enviournment
Closes #1400

fix(client): dynamic protocol for socket.io

---

package.json

Install karma executable into `node_modules/.bin`, which is prefixed to `$PATH` when using `npm run`

Use `bin` field in package.json

---

lib/server.js

When loading many files, it is possible that the webserver and browsers
will start before file preprocessing has completed. This causes the
browser to attempt to connect and timeout and need to be relaunched.
This change will cause the server to wait to start the webserver and
browsers until after all files have been preprocessed. When a browser
connects to the webserver, the webserver will be able to start serving content
immediately and the browser will not experience any connection errors or
timeouts.

fix(server): Start webserver and browsers after preprocessing completed

---

test/unit/server.spec.coffee

Adds 4 unit tests for the server:
- should start the web server after all files have been preprocessed
successfully
- should start the web server after all files have been preprocessed
with an error
- should launch browsers after the web server has started
- should try next port if already in use

test(server): Add basic server unit tests

---

lib/launchers/process.js

We have seen very occasional hangs where the browser fails to capture and then
also fails to exit on SIGKILL.  This results in karma hanging waiting on the
browser to restart.  It is not great to leave zombie processes around, but it is
worse to hang.
This change makes karma continue if SIGKILL doesn't make a spawned process
exit in reasonable (killTimeout) time.

fix(launcher): Continue with exit when SIGKILL fails

---

lib/preprocessor.js
test/unit/preprocessor.spec.coffee

Don't lookup the list of patterns of files to preprocess until the
preprocessor is called. This because patterns might be added after the
preprocessor is created, and those will be missed if the patterns are
looked up too early.
Closes #1340

fix(preprocessor): Lookup patterns once invoked

---

docs/intro/04-faq.md

Hello! 
I was reading through the FAQ, and figured that `0.12.*` might be missing in the list of stable Node versions.
That said, keep up the good work! :+1:

docs(FAQ): Add missing Node + iojs version details

---

requirejs.config.tpl.coffee
requirejs.config.tpl.js

by removing the base path and file extension. This will mean sub dependencies of the test files will not be loaded as-is.
See https://github.com/karma-runner/karma/issues/513#issuecomment-48616784
Fixes https://github.com/karma-runner/karma-requirejs/issues/36 and linked
The docs will need updating too, but wasn't sure where (do I just edit 0.12 docs ?)

Make the requirejs config template normalize paths

---

lib/events.js
lib/file_list.js
lib/helper.js
lib/launcher.js
lib/launchers/base.js
package.json
test/unit/launcher.spec.coffee
test/unit/launchers/base.spec.coffee
test/unit/launchers/process.spec.coffee
test/unit/launchers/retry.spec.coffee
test/unit/middleware/karma.spec.coffee
test/unit/middleware/source_files.spec.coffee
test/unit/middleware/strip_host.spec.coffee
test/unit/reporter.spec.coffee
test/unit/server.spec.coffee
test/unit/web-server.spec.coffee

Bluebird is faster, more spec compliant and has a much better set of built in tooling.
Replaces #1440

refactor: Replace q with bluebird.

---

lib/file_list.js

Changing to the latest version of the glob module means that
karma no longer follows symlinks to find files to serve.
Setting foillow:true in the glob options enables this
behaviour again.

fix(file_list): follow symlinks

---

docs/dev/05-plugins.md

Just a small typo correction in the Plugins section of the docs.

docs(plugins): fixes typo

---

client/stringify.js
package.json
test/client/.eslintrc
test/client/stringify.spec.js

DOM elements and nodes are now serialised using dom-serrialize.
Closes #1106

fix(client): serialise DOM objects

---

lib/middleware/karma.js
test/unit/middleware/karma.spec.coffee

serve files to load at /context.json

feat(runner): serve context in JSON format for JS-only environments

---

lib/web-server.js
test/unit/web-server.spec.coffee

When the `file_list_modified` event was being emitted, the filesDeferred
was simply being resolved again; this has no effect and subsequent
calls to `filesPromise.then` continued to be resolved with the old
files.
This had the effect that issuing `karma run` did not result in new test
files being served.
This has been fixed by reverting the changes to `web-server.js` made in
fabdbae.

fix(web-server): Correctly update filesPromise on files updated

---

docs/dev/04-public-api.md
lib/cli.js
lib/index.js
lib/server.js
test/unit/server.spec.coffee

This adds a slew of new api possibilities to the server. All main
events
from the `globalEmitter` are now emitted on the `server` instances and
publicly available.
For a list of available events see the docs file.
BREAKING CHANGE:
The public api interface has changed to a constructor form. To upgrade
change
```javascript
var server = require(‘karma’).server
server.start(config, done)
```
to
```javascript
var Server = require(‘karma’).Server
var server = new Server(config, done)
server.start()
```
Closes #1037, #1482, #1467

feat(server): improve public api

---

lib/cli.js
test/unit/cli.spec.coffee

Start adding better CLI args validation (#603). Validate log-level to start. This doesn't close the issue.

feat(cli): Better CLI args validation

---

lib/index.js
lib/server.js

This adds `start` method back to the object exported by `lib/server.js`.
Closes #1500

fix: restore backward compatibility for karma@0.13

---

lib/preprocessor.js
test/unit/preprocessor.spec.coffee

Use lower case file extension to detect if it is binary
Closes #1508

feat(preprocessor): Capital letters in binary files extenstions

---

lib/middleware/runner.js
test/unit/middleware/runner.spec.coffee

The runner middleware was starting a file list refresh before executing
a test run, but was not waiting for it to complete. This meant that the
context.html generation would often not see the new file list, and so
stale test files would be served.
I haven't actually managed to successfully run the client tests on my machine, but I *think* this change shouldn't have any adverse impacts. Everything should be assuming that the code in the runner is all asynchronous anyway. I did have to update some of the runner unit tests to match this assumption though.

fix(runner): Wait for file list refresh to finish before running

---

lib/server.js

In limited execution environments the setTimeout/clearTimeout functions
need to be delegated to, rather than stored as references.
This is a follow up to #1519

Updated timers for limited execution environment

---

client/main.js

Added core-js es5 shim in client/main.js
It fixes for me the issue with IE8 which was preventing me to use karma runner to run tests on IE8

Add core-js es5 shim to karma client, fixes #1529

---

lib/file-list.js

When i upgraded to from Karma 0.12.x to 0.13.3, my karma setup stopped working.
file-list.js uses ES6 Array.prototype.find which of course fails with `TypeError: undefined is not a function` in normal node installations (without the harmony flag).
Replacing Array.prototype.find() with lodash.find() (which is already used in other places in file-list.js) seems to fix the issue.

use lodash find() instead of Array.prototype.find

---

static/client.html
static/context.html
static/debug.html

Add meta tags in static html files

feat(static): Support media queries

---

lib/reporter.js
test/unit/reporter.spec.js

I stumbled upon a bug where no column number was given in an error which broke the source-maps.
Not sure if using NaN here as a column number is something you guys like and also the changes to the formatting are dubious. Would appreciate suggestion to improve those.

Fix sourcemaps for errors that don't contain column information

---

lib/file-list.js
test/unit/file-list.spec.js

file-list - file_list_modified should be emitted before refresh promise resolves
Runner test execution is scheduled after file-list refresh resolves.  The web-server gets the file-list from the last file_list_modified event. This was resulting in a race condition where the web server would grab a stale file list.
Closes #1550

fix(file-list): refresh resolves before 'file_list_modified' event

---

docs/plus/03-jenkins.md

Reading that a plugin is optional can make confusion: readers may not install plugin.
Users can not undersand next steps of documentation, based on this plugin.

docs(config): notice users about optional but used plugin

---

lib/config.js
test/unit/config.spec.js

I forgot that the `browsers` option must be an array. This commit catches this case and throws a more descriptive error instead of something a long the lines of `TypeError: undefined is not a function`
I *think* I've got everything formatted properly. Happy to make changes.

fix(config): Error when browers option isn't array

---

lib/config.js
test/unit/config.spec.js

Set up config object with CLI arguments, before passing it to karma config

feat(scope): Pass CLI arguments to karma.config.js. Closes #1561

---

.travis.yml
docs/intro/01-installation.md
docs/intro/04-faq.md
package.json

chore(*): Tweak supported Node.js versions, drop io.js
Current setup means karma won't be tested on future updates to the Node v4
line. Those updates are not allowed to introduce breaking changes and only
the newest one is officially supported so that's the one that should be tested.
In the same way, ythe config doesn't contain "0.10.0" or "0.12.0" but
"0.10" & "0.12" so it catches latest updates.
io.js testing has been dropped - io.js has no official support policy as
opposed to Node.js; also, it won't see any major releases.
Refs 6b8d30f234aa77c87ac8cd720114c90a66e7e88e

Tweak tested/allowed Node.js/io.js versions

---

lib/reporter.js
test/unit/reporter.spec.js

Previously, any error log message containing the words `absolute` or `base` would have those words munged by the error formatter.
Contains broken tests, and fix.

fix(reporter): preserve base/absolute word in error

---

docs/config/01-configuration-file.md
lib/middleware/common.js
lib/web-server.js
test/e2e/headers.feature
test/e2e/support/headers/foo.js
test/e2e/support/headers/test.js

This pull request adds support for custom headers for files served.
My motivation:
This is important for Service Workers. In order to use service workers where the SW's are located in a different location than the html file they are referenced, a special header needs to be set.
Setting this header allows one to write tests for multiple service workers (as they'd be served from different places than debug.html for instance).

Add support for custom headers for file served

---

lib/reporter.js
package.json

The reporter functionality was pulling the entire memoizee library with all its dependencies for a simple memoization solution, and using almost none of the functionality. This seems like not the most critically performant codepath. This PR replaces that with a good-case solution that lowers the dependency footprint.

feat(reporter): Replace memoizee library with a trivial solution.

---

lib/reporter.js
package.json

The reporter functionality was pulling the entire memoizee library with all its
dependencies for a simple memoization solution, and using almost none of the
functionality. This seems like not the most critically performant codepath. This
PR replaces that with a good-case solution that lowers the dependency footprint.
Version 2: WeakMap.

feat(reporter): Replace way-too-big memoizee with a trivial solution.

---

docs/config/05-plugins.md

fix a small typo in the plugin docs.

docs(plugin): fix typo with inline plugin example.

---

docs/config/01-configuration-file.md
lib/web-server.js
test/unit/web-server.spec.js

Took a crack at a simple way of adding custom middleware.
Closes #1612

feat(web-server): allow injection of custom middleware.

---

client/karma.js
docs/config/01-configuration-file.md
lib/config.js
lib/server.js
test/client/karma.spec.js

When autoWatch=true and restartOnFileChange=true, this will "complete"
the current run immediately then schedule a new one as before. This is
most useful in gulp/grunt/etc. tasks that auto-build/test/reload to reduce
the time-to-feedback when making many changes in quick succession.

feat(config): add restartOnFileChange option

---

lib/middleware/proxy.js
test/unit/middleware/proxy.spec.js

The `protocol` parameter is necessary to allow proxying of an HTTPS server.

fix (proxy): Pass protocol in target object to enable https requests.

---

client/karma.js

...full page reload.
Refer to http://stackoverflow.com/questions/29352578/some-of-your-tests-did-a-full-page-reload-error-when-running-jasmine-tests
and
https://github.com/karma-runner/karma/issues/1101

fix (client/karma): Set reload context flag to avoid full page reload

---

config.tpl.coffee
config.tpl.js
config.tpl.ls
docs/config/01-configuration-file.md
lib/config.js
lib/launcher.js
package.json
test/unit/launcher.spec.js

Especially services like Browserstack and SauceLabs have limitations on
how many browsers
can be launched at the same time. The new config option `concurrency`
allows to
specify an upper limit of how many browsers are allowed to run at the
same time.
Ref: https://github.com/karma-runner/karma-sauce-launcher/issues/40
Closes #1465

feat(launcher): Add concurrency limit

---

docs/plus/03-jenkins.md

Current versions of the `karma-junit-reporter` and the given sample configuration store the report below directories named after the browsers the tests were run in, which must be reflected in the Jenkins configuration.
We recently ran into this issue after we updated to `karma-junit-reporter` 0.3.7, and noticed that the documentation in the [Karma documentation](https://github.com/karma-runner/karma-junit-reporter) did not reflect these changes (but the original [karma-junit-reporter](https://github.com/karma-runner/karma-junit-reporter) documentation does). So I'd suggest the documentation changes in this PR, but feel free to adapt/change them, especially since I'm not a native speaker.

docs(jenkins): Update Jenkins documentation

---

client/karma.js

We need to wait for the iframe to be loaded before we can set
reloadingContext to false.
Closes #1652

fix(client): Wait for iframe to be loaded

---

docs/intro/01-installation.md

This was inspired in part by https://github.com/bensu/doo/pull/46. 
Is the recommendation to always use `karma-cli`, even if you're on Unix where you could run `./node_modules/karma/bin/karma start`? Or is running `./node_modules/karma/bin/karma start` acceptable if you don't need to be cross platform?

Recommend using `karma-cli` if you are on Windows

---

docs/plus/01-requirejs.md

"We do this **is** `test/test-main.js`."
"We do this **in** `test/test-main.js`."

Fix RequireJS documentation typo

---

.travis.yml
lib/middleware/proxy.js
package.json

Node 5 includes npm 3 by default so we don't have to update npm to make sure
it works on that version. On the other hand, most people don't upgrade npm
and just use the default included version, especially that it's very hard
to update npm on Windows. It's good to make sure Karma still works with npm 2,
especially that Node 4, current LTS will never upgrade to npm 3.

chore(travis): Test on Node 5, don't update npm in newer Nodes

---

docs/intro/04-faq.md

Add link to TeamCity integration page. Reorder CI list alphabetically.

docs(runner): Add missing link to TeamCity integration page

---

test/unit/file-list.spec.js

Have file-list.js use path.posix instead of path itself, so the tests can expect a '/' separator on any platform.
Closes #1028

test(file-list): Use path.posix to fix tests when run on Windows

---

lib/preprocessor.js
test/unit/preprocessor.spec.js

Change minimatch call to match files with dots in the directory name while preprocessing. Previously these files would be ignored by the preprocessor.

fix(preprocessor): Directory names with dots

---

docs/config/01-configuration-file.md
lib/middleware/proxy.js
test/unit/middleware/proxy.spec.js

Feature(proxy): Allow to configure changeOrigin option of http-proxy

---

lib/middleware/source_files.js

The `middleware:source-files` logger was spelled incorrectly.

fix(middleware): Correct spelling of middleware logger name

---

docs/config/01-configuration-file.md
lib/cli.js

Feature add .config/karma.config.js to default lookup path

---

client/karma.js
docs/config/01-configuration-file.md
lib/config.js
test/client/karma.spec.js

Enable a clearContext config which when set to false:
- prevents clearing of context window upon completion of running of the tests.
- always (re)sets up context regardless of errors
This configuration is useful when embedding the Jasmine html reporter within the context window.

feat(config): Add a clearContext config to prevent clearing of context

---

lib/config.js

Typo was introduced here, ~2 years ago: https://github.com/pavelgj/testacular/commit/27b8d678cdc43f823d2531d25fc548d542dc9078

docs(config): typo

---

docs/config/01-configuration-file.md
lib/cli.js
lib/config.js
lib/middleware/runner.js
lib/runner.js
lib/server.js
test/unit/middleware/runner.spec.js
test/unit/mocha-globals.js
test/unit/runner.spec.js

This feature allows the user to specify if running the runner or server (singlerun) should return non-zero exit code when executing an empty test-suite. The field `failOnEmptyTestSuite : boolean` is added to the configuration file with default value `true`.
**The problem:** If the option is set to `false` and an empty test-suite is executed then the program should exit with exit-code `0` and display a warning. 
**The solution:** Can be divided into two sub-problems:
1. Adding the feature to the server for single-run executions
2. Adding the feature to the runner.
The first case is relatively simple: Besides adding the above option to the configuration file, only an extra check needs to be added at `lib/server.js:254`. 
The second case however is a bit more tricky:
Sending the …

Feature do not fail when the test set is empty

---

client/karma.js
docs/config/03-browsers.md
lib/config.js
lib/launcher.js
lib/launchers/base.js
lib/server.js
test/e2e/displayname.feature

Custom browser-names can now be defined as described in the docs. Furthermore, as a side-effect, browser-names can also be defined when testing manually. This is done by adding the argument `displayName=<displayName>` to the query-string.

Feature allow custom browser names

---

lib/cli.js
lib/init.js
lib/logger.js
lib/middleware/runner.js
lib/reporter.js
lib/reporters/base.js
lib/reporters/dots.js
lib/reporters/dots_color.js
lib/reporters/progress.js
lib/reporters/progress_color.js
lib/runner.js
lib/server.js
test/unit/reporters/base.spec.js

This will solve #1067 but also make some quite invasive changes. Including changing the constructor of the std. reporters. Since these should be generated with injection (according to [this todo](https://github.com/karma-runner/karma/blob/master/lib/launchers/base.js#L22)) this might not be such a big change after all. 
Furthermore this allows setting the `color` properties on an adapter for deciding if a given reporter should write to it.

Feature adding no colors to run command

---

docs/config/01-configuration-file.md
lib/config.js
lib/launchers/retry.js

Allow specification of retry limit in configuration file with the `retryLimit` property. 
I also reordered the entries in the documentation in alphabetical order.
Closes #1126

feat(launcher): Enable specification of retry-limit

---

lib/runner.js
test/unit/runner.spec.js

This slices the buffer rather than modifying it. The buffer slice is returned, with the exit code, as an object:
```js
{
exitCode: int,
buffer: Buffer
}
```

fix(runner): Remove null characters from terminal output

---

lib/middleware/common.js
test/unit/middleware/karma.spec.js
test/unit/middleware/source_files.spec.js

On Node 5.6.0, Karma stopped working with the following error message: `The header content contains invalid characters`. It's caused by the fact that the dates put by Karma to the `Expires` headers contain the time zone name, which might look like `Thu Jan 01 1970 02:00:00 GMT+0200 (Иксанија)` if a Cyrillic locale is used. While Node <5.6 allowed Cyrillics in the HTTP headers, the version 5.6.0 is much stricter. See the changelog https://github.com/nodejs/node/blob/v5.6.0/CHANGELOG.md

fix: invalid characters in the headers on Node 5.6.0

---

docs/dev/04-public-api.md
lib/server.js
test/unit/server.spec.js

Sometimes, when you want to use karma port programatically (e.g. to send manually browser to karma localhost:<port> address), you face problem with not knowing exact port number.
Port number might be different from one set in config as sometimes you run more than one instances of karma. Below image show such situation:
This PR adds 'listening' event to karma. After this event you are sure that you have correct karma port number.
You may use it like this:
```
let server = new Server(karmaConfig, done);
server.once('listening', function (e, port) {
console.log(port); //port number from event
console.log(server.get('config').port); // also correct value
});
```

feat(server): add 'listening' event with port number

---

lib/reporter.js
test/unit/reporter.spec.js

There is no way to resolve source maps in this case anyway. Fixes #1274.

fix(reporter): Disable source maps for URLs without line number

---

test/unit/reporter.spec.js

Before, the exception was thrown in MockSourceMapConsumer's
constructor and not in its originalPositionFor() function,
which however was the expected thing to happen.
While this is practice the same behavior, it was misleading when reading the test.

fix(test): Throw the expected exception

---

lib/file-list.js
package.json
test/unit/file-list.spec.js

Fixes #1859 
I can't see that the cancellation is needed in this case as the promise that is cancelled is a runaway promise anyway.

chore(dependencies): update bluebird v.3

---

docs/plus/02-travis.md
docs/plus/04-semaphore.md

* Double quotes instead of single quotes

docs(config): Use double quotes for json

---

docs/config/01-configuration-file.md
docs/dev/04-public-api.md
lib/cli.js
lib/config.js
lib/detached.js
lib/index.js
lib/logger.js
lib/middleware/runner.js
lib/middleware/stopper.js
lib/runner.js
lib/server.js
lib/stopper.js
lib/web-server.js
package.json
test/e2e/steps/core_steps.js
test/e2e/stop.feature

This is a fix for issue #136. This: 
* Add detached mode using the `karma start --detached` command.
* Add middleware for stopping a server (detached or not).
* Described the detached option.
Any pointers on testing this or describing the new command (`karma stop`)?

Add possibility to stop a karma server

---

docs/config/01-configuration-file.md
lib/config.js
lib/middleware/karma.js
test/e2e/custom-context.feature
test/e2e/steps/core_steps.js
test/e2e/support/context/context2.html
test/e2e/support/context/test.js
test/unit/config.spec.js
test/unit/middleware/karma.spec.js

Continuation of https://github.com/karma-runner/karma/pull/1586 and https://github.com/karma-runner/karma/pull/1360
Potential progress/fix for https://github.com/karma-runner/karma/issues/1752

feat(config): Allow custom context and debug files

---

lib/middleware/karma.js
test/unit/middleware/karma.spec.js

Change a line to escape single quote characters in filenames.
Closes *[#1876](https://github.com/karma-runner/karma/issues/1876)*

fix(karma): Fix issue regarding escape quotes

---

docs/config/04-preprocessors.md
docs/dev/01-contributing.md

Fix broken links in the documentations at:
- dev\contributing.md
- config\preprocessors.md

fix(docs): Fix broken links in documentation

---

lib/launcher.js
lib/plugin.js
lib/preprocessor.js
lib/reporter.js
lib/server.js
test/e2e/load.feature
test/unit/launcher.spec.js
test/unit/preprocessor.spec.js

Stop karma if a launcher, reporter, plugin, or preprocessor fails to
load, after attempting to load each of them, and reporting errors for
each load error. 
~~Also someone should prob. tell @nikku that the karma-browserify 
plugin is going to stop working due the changed signature of 
`createPreprocessor`.~~
Closes #855

feat: Fail on load-errors.

---

.travis.yml
scripts/validate-commit-msg.sh

When working on a repo, I like to commit frequently in a working branch. The `ghooks` were getting on my nerves so I removed them.
However, I have realized that I was able to open #1984 with a bad commit message format as a result. To remedy that, I'm adding the commit message validation to Travis CI.
In this PR:
- Added `validate-commit-msg` to `npm run travis` to enable non-local message validation

Added commit message validation to Travis CI

---

docs/config/02-files.md
lib/config.js
lib/file-list.js
lib/helper.js
test/e2e/files.feature
test/e2e/support/files/log_foo.js
test/e2e/support/files/test.js
test/unit/helper.spec.js

Do not include a file, when `include=false`.
Give `include=false` precedence over `include=true`.
Closes #1530

fix(files): Ignore included:false pattern

---

lib/helper.js

As reported in #2000, the current `master` is failing on Windows due to `customContextFile` being `null`. In this PR:
- Updated `replaceWinPath` to check for value being a string rather than not being undefined
- Fixes #2000
Here's AppVeyor failing on the current `master` and passing with our patched branch:
https://ci.appveyor.com/project/twolfson/karma-electron-launcher/build/94/job/dpsv7d5nv0sxcj6a
https://ci.appveyor.com/project/twolfson/karma-electron-launcher/build/95/job/vjt895wok3qwgvo3

fix(helper): Patched replaceWinPath from choking on `null` values

---

package.json

As explained in #2002, we thought Node.js@0.12 wouldn't have issues since we had Node.js@5.0 running. Unfortunately, our `xcopy` methodology was space intensive and didn't work for `npm@2` (which is what Node.js@0.12 uses).
We got this repaired via an `npm` upgrade but found out that our previous attempt at symlinks was invalid. Now that we got it working, it's a much better approach than `xcopy`. In this PR:
- Moved from `xcopy` to symlinks for `node_modules/karma`
- Repairs failing AppVeyor builds on `master`
**Passing builds:**
https://ci.appveyor.com/project/twolfson/karma/build/31

Repaired AppVeyor for Node.js@0.12

---

docs/config/01-configuration-file.md
lib/middleware/karma.js
test/client/karma.conf.js
test/e2e/support/tag/tag.js
test/e2e/support/tag/test-with-version.js
test/e2e/support/tag/test-without-version.js
test/e2e/tag.feature

Add the configuration to add a javascript version tag to the loaded scripts. Only applied when the Firefox browser is run.
Closes #1719.

feat(config): Add configuration for adding javascript version.

---

docs/config/01-configuration-file.md

Before this change, the documentation for singleRun stated that the CLI
commands were "--single-run, no-single-run". "no-single-run" requires
the double dash in order be used.  This commit adds the "--" prefix.

docs: Add '--' to 'no-single-run' documentation

---

.travis.yml

Node 0.10.44 updated npm to v2 (as a security update) so there's no need
to update it manually anymore.

chore(package): don't update the included npm in Node

---

client/karma.js
gruntfile.js
lib/middleware/karma.js
static/context.html
static/context.js
static/debug.html
static/debug.js
test/client/karma.spec.js
test/e2e/support/context/context2.html

**Depends on #2019, please only review HEAD commit**
In #1984 we discussed removing `karma.store` as it's no longer used and not portable to environments like Electron (due to wanting to share a `store` across multiple processes).
https://github.com/karma-runner/karma/pull/1984#discussion_r57228714
In this PR:
- Removed `store` implementation from `client` and `debug` environments
- Removed `store` tests

chore(store): Removed unused store implementation

---

CHANGELOG.md

Fixes issue in which a code block inside a list was mistakenly rendered inline with the language name visible.
It is currently rendered like this:
Now it's like this:

Fixes code block rendering issue in contributing file.

---

lib/reporter.js
test/unit/reporter.spec.js

- Avoid prepending basepath to every file path.
The original path is usually relative to the project, and much more meaningful
than basepath + path, which is usually a long, absolute path.
- Format as [mapped location] <- [original location]
The mapped location is the more important part for users, it's the source
file they are working on.
- Resolve source map file paths relative to the original file path.
It's common for tools that generate a source map to not have a complete
understanding of what paths they should generate, in which case they just use
the local path. An example tool is TypeScript.
Resolving the path against the original file path makes these paths
unambiguous in the project.

feat(reporter): improve source map handling and reporting.

---

lib/launchers/process.js

@dignifiedquire This is in response to bug we are seeing where karma hangs because it is unable to force kill chrome, possibly https://github.com/karma-runner/karma/issues/24#issuecomment-216249098

fix(launcher): send sigkill on timeout when force killing

---

lib/middleware/runner.js
test/unit/middleware/runner.spec.js

Before this change, calling `karma run` would overwrite any value in config.client.args with the value provided in the `karma run` request, even if that value was an empty array. This commit does a _.merge to merge the two values together.
Fixes #1746

fix(runner): Merge config.client.args with client.args provided by run

---

docs/config/01-configuration-file.md
lib/web-server.js
test/unit/web-server.spec.js

This adds a `beforeMiddleware` option to the config. This allows the user to inject middleware before karma's middleware are ran. My use case is blocking the tests on refresh while the tests are recompiling (to prevent old test files from being served).

feat: adding support for before middleware

---

lib/config.js
lib/server.js

We’re encountering a problem where sometimes Karma just disconnects and stops running tests until we restart Karma manually.
We found that some of our JavaScript code intermittently gets stuck when running tests — that Karma considers it a time out. One such example is an infinite loop in the code.
Looking at other issues (https://github.com/karma-runner/karma/issues/598, https://github.com/karma-runner/karma/issues/1514) suggests adding `browserDisconnectTolerance`. I’ve tried that and several other options to no avail.
From further source code inspection, in 19590e1f66fd6c3b0d3fc9e90000c705198e0e70 it turns out that __`browserDisconnectTolerance` is only active in `singleRun` mode.__ This pull request makes `browserDisconnectTolerance` work in non-singleRun mode.
Here’s a test case to …

Allow browserDisconnectTolerance to be set in non-singleRun mode.

---

lib/server.js
test/e2e/middleware.feature
test/e2e/pass-opts.feature
test/e2e/proxy.feature
test/e2e/support/middleware/middleware.js
test/e2e/support/middleware/test.js
test/e2e/support/proxy/plugin.js
test/e2e/support/world.js
test/unit/server.spec.js

The `Server.prototype._start` function was injected with `webServer` and `socketServer`. This prevents frameworks from being able to manipulate `config.middleware` before those servers are created.
The solution is simply to defer injection until after all frameworks have loaded, and then fetch those values with `injector.get`.
There were no e2e tests involving middleware. I have added two, including one that verifies the new capabilities.
The second commit adds a test verifying that `config.proxies` can be configured by frameworks now as well (Fixes #1110)

Allow frameworks to inject middleware

---

lib/config.js
lib/reporter.js
lib/reporters/base.js
lib/reporters/dots.js
lib/reporters/dots_color.js
lib/reporters/progress.js
lib/reporters/progress_color.js
package.json
test/e2e/browser_console.feature

fix(server): log browser messages to the terminal

---

lib/reporters/base.js

This was introduced by https://github.com/karma-runner/karma/commit/d1f924c7#diff-5c8a5788ecd4b4af2a29bc27ac4ae986R140 and is thus printed in every test run.

Remove console.log

---

lib/reporters/base.js

* `'config.browserLogOptions'` -> `'config.browserConsoleLogOptions'`

fix(reporter): inject correct config option

---

config.tpl.ts
docs/config/01-configuration-file.md
lib/cli.js
lib/config.js
lib/init/formatters.js
test/unit/cli.spec.js

- Add TypeScript support for `karma.conf.ts`
This should address #1727.

feat(config): add support for TypeScript

---

lib/middleware/karma.js
test/unit/middleware/karma.spec.js

**The Problem**
When an error occurs in a script that is not served by the
default server spawned by karma, the stack trace gets lost and
only the message `"Script Error"` is captured and reported back.
This makes it hard to pin-point where the error originated from.
**The Solution**
Add `crossorigin` attribute to generated script tags.
Solution is inspired by this article:
https://blog.getsentry.com/2016/05/17/what-is-script-error.html

fix: Add crossorigin attribute to script HTML tags

---

docs/dev/04-public-api.md

Was:
```js
var stopper = require('karma').stopper
runner.stop({port: 9876}, function(exitCode) {
```
Changed to :
```js
var stopper = require('karma').stopper
stopper.stop({port: 9876}, function(exitCode) {
```

fix(docs): fix stopper.stop wrong variable name. closes #2244

---

lib/middleware/common.js

fix WARN logs for undefined error handler

---

client/karma.js
context/karma.js

As reported in #2239, our current `postMessage` hook is looking at all post messages, not only the ones for Karma. In this PR:
- Moved to namespaced `postMessage` variable checks
- Updated `postMessage` logic to only assert if a truthy method was given
- Fixes #2239 
/cc @dignifiedquire

fix(context): Updated postMessage listener to stop validating non-Karma messages

---

lib/file-list.js

Thanks to @m-a-r-c-e-l-i-n-o for pointing me in the right direction
Fixes #2194
This supersedes #2255 
Also fixes 
- https://github.com/karma-runner/karma-jasmine/issues/127
- https://github.com/karma-runner/karma-mocha/issues/102
- https://github.com/karma-runner/karma/issues/2237

fix(file-list): ensure patterns are comparable

---

docs/intro/01-installation.md

Update to include jasmine-core in install doc, which is a peer dependency of karma-jasmine

docs: include jasmine-core in installation instructions

---

lib/launchers/process.js

If you manage to make chrome emit errors in the console, like we do with webrtc, the node stream buffer for stderr fills up and locks up the browser. This just calls `.resume()` to prevent that.
Here's a tarball of a simplified project that repro's the issue:
https://drive.google.com/file/d/0By71SGpctHHxVzl1bkx6bGg3b2c/view?usp=sharing
Simply run `karma start --browsers ChromeFakeDevices` and chrome should lock up when it's done around 200 of the 1000 identical tests.

Call .resume() on process streams so they don't get blocked

---

docs/config/02-files.md
lib/middleware/common.js
lib/middleware/karma.js
lib/middleware/source_files.js
test/unit/middleware/source_files.spec.js

Adds the ability to use Range headers in the web server (#2140).

feat(web-server): Allow Range headers in web server.

---

lib/middleware/source_files.js
test/unit/middleware/source_files.spec.js

Karma fails on Jenkins (standard "Multibranch pipeline" project) when it checks out branches containing '/' as it replaces '/' by '%2F' in the folder name.
Alternatively, if the project parent folder contains %2F in its name, karma will not execute properly.
Fixes errors seen on #1751, #61.

fix(web-server): Allow karma to run in project which path contains HTML URL encoded characters

---

lib/middleware/common.js
package.json
test/unit/middleware/source_files.spec.js

Added one new dependency, use `range-parser` (Express dependency) to compute range.
It is more well-tested in the wild.
Fixes #2310

fix(middleware): ensure Range headers adhere more closely to RFC 2616

---

ISSUE_TEMPLATE.md

Behavior/behaviour is both correct spelling; changed for consistency.

docs(gh): fix typos

---

docs/config/01-configuration-file.md
lib/cli.js
lib/config.js
lib/reporter.js
test/unit/cli.spec.js
test/unit/config.spec.js
test/unit/fixtures/format-error-property.js
test/unit/fixtures/format-error-root.js
test/unit/reporter.spec.js

Fixes #2119.  This PR allows a `formatError` config function.  The function receives the entire error message as its only argument.  It returns the new error message.

feat(reporter): add config formatError function

---

client/constants.js
client/main.js
docs/config/01-configuration-file.md
lib/config.js
lib/launcher.js
lib/middleware/karma.js
test/e2e/steps/core_steps.js
test/e2e/support/after_hooks.js
test/e2e/support/behind-proxy/plus.js
test/e2e/support/behind-proxy/test.js
test/e2e/support/proxy.js
test/e2e/support/world.js
test/e2e/upstream-proxy.feature
test/unit/config.spec.js
test/unit/launcher.spec.js
test/unit/middleware/karma.spec.js

I have a use case where I can only load content via a web proxy that I don't control. This web proxy prepends a directory to the front of URLs which breaks the internal urls inserted by the Karma middleware.
This pull request adds an `upstreamProxy` option that allows the additional proxy path to be configured and used in URLs. To complete the use cases and implement e2e tests I also added `hostname`, `port` and `protocol` fields to use in launchers to point them at the proxy.
This is my first contribution here so please be gentle ;)

feat: upstreamProxy config option to deal with proxies

---

CONTRIBUTING.md

There is a broken link in CONTRIBUTING.md, due to an incorrect reference to the `[egghead_series]` link written as:
```
[How to Contribute to an Open Source Project on GitHub](egghead_series)
...
...
[egghead_series]: https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github
```
which _incorrectly links to_: https://github.com/karma-runner/karma/blob/master/egghead_series and not https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github
The surrounding parentheses should be **square brackets** in order to correctly use the reference-style link ( See this markdown cheat sheet for more info: https://blueskyworkshop.com/tools/markdown/markdown-cheatsheet.html#Links )
**Proposed change:**
```
[How to Contribute to an Open Source Project on …
```

Fix #2207: Fix markdown syntax(broken link) for CONTRIBUTING.md

---

docs/config/01-configuration-file.md
lib/config.js
lib/middleware/karma.js
test/unit/middleware/karma.spec.js

As described in #2249, external scripts without the necessary `Access-Control-Allow-Origin` header are rejected with:
```
Script from origin '...' has been blocked from loading by 
Cross-Origin Resource Sharing policy: 
No 'Access-Control-Allow-Origin' header is present on the 
requested resource. Origin '...' is therefore not allowed access.
```
This PR reverts the change that introduced this behavior. 
If we want to keep the benefits that were introduced with #2219 we could create a configuration option for this. 
In that case we'd have to decide what we want as a default behavior.

fix(runner): Fix loading of external scripts without cors headers

---

docs/config/01-configuration-file.md

I'm getting the following error when I try to use karma (version 1.3.0) without installing all required plugins for browsers:
```
14 10 2016 00:05:46.171:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
14 10 2016 00:05:46.173:ERROR [launcher]: Cannot load browser "PhantomJS": it is not registered! Perhaps you are missing some plugin?
14 10 2016 00:05:46.173:ERROR [karma]: Found 1 load error
```
Update documentation based on the required plugins for each browser.

All browsers in config require external plugins

---

lib/reporter.js
test/unit/reporter.spec.js

This was causing some excruciating error logs with the default format of cross-domain iframe errors:
```
Error: Blocked a frame with origin "http://localhost:9876" from accessing a cross-origin frame.
at Error (native)
at Function.method.restore (absolute/var/folders/8m/vg2kf8h50bj9gy5r9gwn20dw00_y0z/T/fa96dc8102e4c5416f4cd38061107a08.browserify?f4458f57b50ae627f718945da619dae7c682b4a0:60376:28)
at each (absolute/var/folders/8m/vg2kf8h50bj9gy5r9gwn20dw00_y0z/T/fa96dc8102e4c5416f4cd38061107a08.browserify?f4458f57b50ae627f718945da619dae7c682b4a0:57875:33)
...
```
The old regex would find that `https://` then include everything that wasn't a slash, which included the next two lines into the `/absolute`. The output would be similar to:
```
Error: Blocked a frame with origin …
```

Reporter Sourcemap: Do not allow URL domains to span new lines

---

.npmignore

As described in #2351, the `karma completion` command as listed in `karma --help` does not work because the scripts folder is missing from the published npm package.
- Restore the `scripts` folder to the published npm package by removing it from `.npmignore`
---
Fixes #2351

Fix #2351: Restore scripts from .npmignore to fix karma completion command

---

docs/dev/04-public-api.md
lib/index.js
test/unit/index.spec.js

I would like to be able to only use the `config` part of karma. Using `require('karma/lib/config')` feels like i'm trashing a private party, i would rather be invited  :cake:.

feat(index): Expose config on the index file

---

package.json

- Upgrade glob to an up to date version to avoid regression
This should sufficiently fix #2325.

chore: upgrade glob to 7.1.1

---

package.json

- Upgrade socket.io to v1.7.1, which contains fix for the Uint8Array regression in IE9
This should adequately address #2190.

chore: upgrade socket.io

---

lib/middleware/common.js
package.json

- Update Buffer usage to non-deprecated methods of creating a Buffer
Note that this does not fully fix #2429, as there is a plugin that needs to be looked into. However, it should be noted that these methods were only added in Node 5.10.0, which means that this is a breaking change in order to satisfy Node 7. This should probably be bundled with a major version bump when this is chosen to be merged.

fix(middleware): update Buffer usage

---

docs/config/01-configuration-file.md
lib/config.js
lib/constants.js
lib/server.js
test/unit/server.spec.js

Adding listen address option so that IPv6 and loopback interfaces can be used.

---

docs/dev/04-public-api.md
lib/constants.js
lib/reporters/base.js
test/unit/reporters/base.spec.js

- Do not log lower levels if `browserConsoleLogOptions.level` is set
This should address #2228.

fix(browser): filter browser logging by level

---

context/karma.js
test/client/karma.spec.js

- Capture `window.confirm` & `window.prompt` usages in client
I think this addresses #694, although it is a little vague as to how it is desired to be done

feat(client): capture confirm & prompt

---

lib/config.js
test/unit/config.spec.js

This allows folks using typescript karma config files to do
```
// karma.conf.ts
export default function(config) {
config.set({
basePath: './'
})
}
```

feat(config): allow config to be a default export

---

package.json

ghooks is now deprecated in favour of husky. Also requires your local git checkout to be nuked and started from scratch to uninstall the old ghooks

chore: switch from ghooks to husky

---

lib/config.js
lib/helper.js
lib/launcher.js
lib/launchers/process.js
test/unit/launchers/process.spec.js

Add a new user configurable property processKillTimeout to set timeout for any spawned process
Closes #2447

fix(runner): Make process kill timeout configurable

---

docs/dev/06-git-commit-msg.md

Add an example commit message so contributors can see a concrete example of what is expected.

docs(contributing): add sample commit message

---

.travis.yml
appveyor.yml
docs/intro/01-installation.md
package.json

I'm openning this to improve the node support to v7.
- Update `engine` in `package.json` to support Node v7. 
- Update `travis.yml`  to run env Node v7. 
- Update `appveyor.yml`  to run env Node v7. 
- Update `01-installation.md` adding Node  v7. 
It closes the issue #2559

update node support to v7

---

docs/config/01-configuration-file.md

The list of files showing how Karma finds configuration lists TypeScript, but the note preceding it did not. Small change, nothing crazy.

Modified note on config languages to include TypeScript

---

lib/config.js
lib/constants.js
test/e2e/browser_console.feature
test/unit/reporters/base.spec.js

Additional fix to the next bug:
filter browser logging by level  ([35965d9](https://github.com/karma-runner/karma/commit/35965d9)), closes [#2228](https://github.com/karma-runner/karma/issues/2228)
otherwise `console.log` ignore doesn't work with 
```
browserConsoleLogOptions: {
level: 'debug',
terminal: true
}
```

filter browser logging by level of LOG

---

common/stringify.js
test/client/stringify.spec.js

In https://github.com/twolfson/karma-electron/issues/20, we received a bug report with respect to serializing Electron's remote modules. After some digging, it turns out this was being caused by a serialization attempt on `Proxy` wrapped functions:
https://github.com/electron/electron/blob/v1.6.3/lib/renderer/api/remote.js#L170-L190
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/toString
```js
new Proxy(function x () {}, {}).toString()
// VM594:1 Uncaught TypeError: Function.prototype.toString is not generic
//    at Proxy.toString (<anonymous>)
//    at <anonymous>:1:33
```
Unfortunately, there is no patch/workaround for serializing proxies. Although, they can provide a custom `toString()` function if they want:
```
new Proxy(function x () {}, …
```

fix(client): add proxy support to stringify

---

README.md

change "a" to "an" in README.md on line 45. *"The rule is  that you use a before words that start with a consonant sound and an before words that start with a vowel sound."* Referenced from [Mignon Fogarty](http://www.quickanddirtytips.com/education/grammar/a-versus-an).

docs: ensure grammar is correct in docs

---

package.json

> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
The current version constraint for minimatch (as a production dependency) allows a version that's vulnerable to a denial of service.
https://nodesecurity.io/advisories/minimatch_regular-expression-denial-of-service

Update minimatch dependency to avoid DoS

---

.gitignore
console.log
test/e2e/browser_console.feature

During my recent Karma contribution, I started getting a persistent one-off change in a `console.log` file which got annoying to avoid via `git add -p`:
```diff
$ git diff
diff --git a/console.log b/console.log
index 10d33cb..029f6fe 100644
--- a/console.log
+++ b/console.log
@@ -1,5 +1,5 @@
-PhantomJS 2.1.1 (Mac OS X 0.0.0)
-PhantomJS 2.1.1 (Mac OS X 0.0.0)
-PhantomJS 2.1.1 (Mac OS X 0.0.0)
-PhantomJS 2.1.1 (Mac OS X 0.0.0)
-PhantomJS 2.1.1 (Mac OS X 0.0.0)
+PhantomJS 2.1.1 (Linux 0.0.0)
+PhantomJS 2.1.1 (Linux 0.0.0)
+PhantomJS 2.1.1 (Linux 0.0.0)
+PhantomJS 2.1.1 (Linux 0.0.0)
+PhantomJS 2.1.1 (Linux 0.0.0)
```
This was being caused by a dynamically generated test file that somehow got added to `git`. In this PR:
- Removed `console.log` from `git`
- Relocated `console.log` to …

chore: relocate console.log test file into test/e2e and ignore it

---

docs/config/01-configuration-file.md
lib/middleware/proxy.js
test/unit/middleware/proxy.spec.js

Add a new user configurable property proxy event
[nodejitsu/node\-http\-proxy: A full\-featured http proxy for node\.js](https://github.com/nodejitsu/node-http-proxy#listening-for-proxy-events)

feat(proxy): add proxy events to config

---

context/karma.js
test/client/karma.spec.js

When confirm and prompt were wrapped here https://github.com/karma-runner/karma/commit/3a618b3ce51f7fb8da94636562ba2ed785da0579, returning the results of these methods was forgotten. This fixes that.

fix: return result of confirm and prompt

---

lib/middleware/common.js
lib/middleware/proxy.js
package.json
test/.eslintrc

I had to turn off 'no-unused-expressions' in the test directory since a lot of the mocha expectations look something like:
```javascript
expect(spyRegister).to.have.been.called
```
which eslint thinks has no effect.

chore(package): update eslint-config-standard to version 7.0.0

---

lib/browser.js
test/unit/browser.spec.js

feat(browser): add browser_info event

---

docs/config/01-configuration-file.md
lib/reporter.js
test/unit/reporter.spec.js

I wrote this feature originally and haven't had time to come back and address this issue until now. See https://github.com/karma-runner/karma/issues/2119#issuecomment-248404728.
***
Fixes #2626 
The main purpose of the `formatError` function, per the docs, is to trim down the stack trace.  However, no matter the return value configured, a new line is always appended.  This means even when lines are removed a blank new line is still added.  This results in large, blank, stack traces:
This PR simply returns the _exact_ value the user has configured in their `formatError` function, without appending a newline to it.  This allows for removing lines from the stack trace:

fix(reporter): keep users exact formatError result

---

lib/launchers/process.js
test/e2e/launcher-error.feature
test/e2e/support/launcher-error/fake-browser.sh
test/e2e/support/launcher-error/specs.js

In https://github.com/twolfson/karma-electron/issues/17, https://github.com/twolfson/karma-electron/issues/22, and personal experience, there's been scenarios when we're setting up Karma in CI and it's erroring out with no useful feedback. Typically this is due to a system dependency (e.g. missed an `apt-get` step).
This PR aims to resolve that by adding `stderr` to the output of failing launchers. In this PR:
- Added `stderr` output to launcher `errorOutput`
- We didn't know if we wanted to be clever and indent everything so we went the simple route for now
**Before:**
```
30 03 2017 04:00:46.897:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
30 03 2017 04:00:46.899:INFO [launcher]: Launching browser Firefox with unlimited concurrency
30 03 2017 04:00:46.906:INFO …
```

feat(launcher): output stderr for failing launchers

---

lib/middleware/karma.js

The for..in loop was not working with mootools because mootools  adds functions to the array prototype.
checking for own property

Does not work with Mootools

---

lib/launchers/process.js
test/unit/launchers/process.spec.js

When it is determined that an error occured during the run of a launch
it's useful to have output from the process.
We just need to know what was going on in order to debug (if necessary)
Related to karma-runner/karma#2663 Complete browser log output when process isn't started
Achieved with 
```bash
folder=/tmp/karma-test
scriptName=faulty-browser.bash
script=$folder/$scriptName
mkdir -p $folder
echo '#!/usr/bin/env bash
echo "Starting..."
sleep 1
>&2 echo "An error was encountered"
exit 1
' > $script
chmod u+x $script
export PATH=$folder:$PATH
export CHROME_BIN=$scriptName
grunt test:client
```

feat(runner): Buffer stdout and stderr for output when errors occur

---

lib/middleware/karma.js

- Change use of for..in to plain for loop due to issues where array prototype is modified
Fixes #2671

fix(middleware): change to use vanilla for loop

---

docs/config/01-configuration-file.md
lib/file-list.js
test/unit/file-list.spec.js

I'm opening this up for feedback early, to make sure I'm on the right track here. My intention is to change the behaviour of `autoWatchBatchDelay` to debounce file change events, and not run the tests until at least `autoWatchBatchDelay` ms have elapsed since the last file change.
Closes #2331

feat(watcher): Debounce autoWatchBatchDelay

---

lib/file-list.js

When using Karma programatically I came across issues which were due to core-js polluting the environment. It turns out that all Karma needs from core-js (whilst karma supports node 0.x versions) is `Map` and `Set`, switching to the file includes for these minimises the amount of core-js being used :-)

fix(file-list): Stop polluting global environment with core-js

---

package.json

See https://github.com/karma-runner/karma/issues/2593

Update Socket.io to 1.7.4 to avoid issue with ws@1.1.2

---

lib/preprocessor.js
test/unit/preprocessor.spec.js

When saving a file in IDEs like Visual Studio, Atom, a dozen operations including read/write/delete/rename are performed on the file. When aggressive antivirus like McAfee is running it could make it even worse, there are nearly 50% chance karma will crash because the file is locked
There were multiple issues raised because of this
#1397
#1213
#959
The solution is retry reading file if fs.readFile fails and throw after 3 failed retries

fix(preprocessor): retry if fs.readFile fails

---

.travis.yml
scripts/validate-commit-msg.sh

There were a couple of problems related to commit message validation:
1. inverted condition in travis beforeinstall check
2. passing path relative to project root to `validate-commit-msg` rather than relative to `.git` directory
With those fixed, the ✅ is back!

Fix Travis commit message checks

---

.mailmap

The contributors file contains two entries for me, at:
https://github.com/karma-runner/karma/blob/69978ee83e42c88b9cb048b2cb7a07d6e5c20e5b/package.json#L46
and:
https://github.com/karma-runner/karma/blob/69978ee83e42c88b9cb048b2cb7a07d6e5c20e5b/package.json#L54
This is because in Unicode `ę` can be written in two ways:
1. As a separate letter: `ę` (`"ę".length === 1`)
2. As "e" plus "Combining Ogonek" ("ogonek" means "a little tail" in Polish; `"ę".length === 2`, try it yourself), see http://www.fileformat.info/info/unicode/char/0328/index.htm
This `.mailmap` entry will collapse those two entries.

Normalize my name in .mailmap

---

gruntfile.js
test/e2e/step_definitions/core_steps.js
test/e2e/step_definitions/hooks.js
test/e2e/support/env.js
test/e2e/support/world.js

Update cucumber tests to address the following incompatibilities:
1. usage of `defineSupportCode` instead of relying on invocation with
appropriate `this` the modules `require`d by cucumber-js
2. replace regex literals with cucumber expression strings, as the
former cause issues when non-existent capture groups are parsed
3. migrate from old-style tag selection syntax
Fixes #2764

test(e2e): fix tests for new cucumber-js

---

client/karma.js

feat(client): Log global error stack trace

---

.travis.yml
docs/intro/01-installation.md
docs/intro/04-faq.md
package.json
test/unit/file-list.spec.js

Updated docs.
Updated engines matcher in package.json.
Updated places where node-0.1-specific code was noted in comments.

fix(build): Drop support for Node 0.10 and 0.12.

---

test/unit/web-server.spec.js

Node 8.8.0 includes a new experimental built-in http2 module which trumps
the external one from npm, breaking Karma tests. This commit switches the
require back to using the npm package.

test(web-server): fix http2 tests

---

lib/config.js

CoffeeScript lost the hyphen in the module name about 9 months ago, all the new versions are going to be released as coffeescript not the coffee-script

Support the new CoffeeScript module name

---

appveyor.yml

appveyor CI fails on node 8 with
Error: EPERM: operation not permitted, scandir 'C:\projects\karma\node_modules\fsevents\node_modules'
See https://github.com/npm/npm/issues/18380

fix(config): Retry install with appveyor-retry.

---

package.json

This is a duplicate of @kevinsalter PR #2821. I am re-sending after appveyor fixup.
(We don't seem to have the ability to retry appveyor builds).
Fixes #2777

fix(deps): update socket.io to version 2.0.3.

---

lib/cli.js
test/unit/cli.spec.js

The cli silently ignores unknown options. Until we can fix this, a simple
improvement is to warn on options with underscores. In our experience, --no_browsers
is common user error that gives confusion because browsers are used.

feat(cli): Warn on commands with underscores.

---

lib/logger.js
package.json
test/unit/config.spec.js
test/unit/logger.spec.js

Support log4js 2.x as well as 1.x for configuration.
Fixes #2858

fix(logging): Upgrade to log4js 2.x API.

---

docs/config/01-configuration-file.md
docs/config/02-files.md
lib/config.js
lib/file-list.js
lib/file.js
lib/middleware/karma.js
test/unit/middleware/karma.spec.js

Adds a manual file type so that users can instruct Karma which method to use when loading a file without an extension (such as Google font files)
Example:
```
files: [
{
pattern: 'https://fonts.googleapis.com/icon?family=Material+Icons',
type: 'css'
}
]
```
Fix for https://github.com/karma-runner/karma/issues/2824
First time working karma so let me know if there are any changes I need to make.

feat(middleware): added manual file type option

---

lib/config.js

Currently the debug message about where the configfile was loaded from is always shown, regardless of the user defined loglevel. I've moved those debug messages to be done after the user's defined loglevel has been set which enables the user to choose whether they see this message or not :-)
Alternative fix the problem described in https://github.com/karma-runner/karma/pull/2658

fix(config): Call debug log methods after setting the loglevel based upon config/cli-options

---

client/karma.js

Resolves #2711
Before:
```
Chrome 59.0.3071 (Mac OS X 10.12.3) ERROR
{
"originalErr": {},
"__zone_symbol__currentTask": {
"type": "microTask",
"state": "notScheduled",
"source": "Promise.then",
"zone": "<root>",
"cancelFn": null,
"runCount": 0
}
}
Chrome 59.0.3071 (Mac OS X 10.12.3): Executed 0 of 0 ERROR (1.348 secs / 0 secs)
```
After:
```
Chrome 59.0.3071 (Mac OS X 10.12.3) ERROR
{
"message": {
"originalErr": {},
"__zone_symbol__currentTask": {
"type": "microTask",
"state": "notScheduled",
"source": "Promise.then",
"zone": "<root>",
"cancelFn": null,
"runCount": 0
}
},
"str": [
"Error: (SystemJS) Object prototype may only be an Object or null: undefined",
"    TypeError: Object prototype may only be an Object or null: undefined",
"        at setPrototypeOf (<anonymous>)",
"        at …
```

Better string representation of errors

---

.npmignore
gruntfile.js
lib/server.js
package.json
test/unit/server.spec.js

Fixes #2884 in a less npm-dependent manner than my previous PR.
@dignifiedquire How do you feel about this solution?

refactor: move compile step to first run of server

---

lib/reporter.js
test/unit/reporter.spec.js

Handle urlRoot in paths if rulRoot specified
Closes #2897

fix(reporter): show file path correctly when urlRoot specified

---

lib/config.js
lib/file-list.js
lib/url.js
test/unit/middleware/karma.spec.js

Currently the file type option does not work with absolute urls, this PR fixes that issue.

fix(middleware): add file type to absolute urls

---

lib/server.js

The async write operation has no callback and errors are not
detected that way. Switch to the sync version to circumvent that
problem.
This will otherwise cause issues from Node.js 10 on. See https://github.com/nodejs/node/pull/18668.

fix(lib): switch to sync write

---

.npmignore
gruntfile.js
lib/server.js
package.json
test/unit/server.spec.js

To support running karma directly out of the repo, 'browserify' is applied dynamically iff the static files are not already available.  The 'browserify' module is loaded only in the case where it will be used: users installing karma from the npm module will not need to apply it and installs using --production will not depend upon 'browserify' or its otherwise unused deps.
This provides an alternative fix for #2884, one that does not require every user to install the browserify deps.
Fixes #2921

 refactor(server): compile on first run if browserify files missing.

---

lib/reporter.js
test/unit/reporter.spec.js

Fixed a problem when config.urlRoot is set to '/' causing the error stack not to be parsed correctly and therefore source maps are not used.

fix(reporter): Fix #2930 causing error stack not to be parsed correctly

---

lib/middleware/common.js

`safe-buffer` is already used and provides `Buffer.alloc` polyfill, so just use `Buffer.alloc` directly to avoid hitting deprecated API.
Refs:
https://nodejs.org/api/deprecations.html#deprecations_dep0005_buffer_constructor
This was overlooked in 3d94b8cf18c695104ca195334dc75ff054c74eec (#2484).
Tracking: https://github.com/nodejs/node/issues/19079

Avoid using deprecated Buffer constructor

---

lib/browser.js

The method "disconnect" sometimes is called without arguments. The emited message should not look broken then.
Previously it looked like this:

fix: Nicer "disconnect" - no more "Disconnectedundefined"

---

docs/config/01-configuration-file.md
lib/middleware/karma.js
test/e2e/support/tag/tag.js
test/e2e/support/tag/test-with-version.js
test/e2e/tag.feature

Support for specifying JavaScript version was removed in Firefox 59. See
https://bugzilla.mozilla.org/show_bug.cgi?id=1428745 for more details.
From now on Karma will ignore `jsVersion` property in Firefox 59+ and
print deprecation warning if `jsVersion` property is set.

fix: ignore jsVersion configuration property in Firefox 59+

---

lib/browser.js
lib/browser_collection.js
lib/browser_result.js
lib/cli.js
lib/completion.js
lib/config.js
lib/constants.js
lib/detached.js
lib/emitter_wrapper.js
lib/server.js
test/unit/browser.spec.js
test/unit/browser_collection.spec.js
test/unit/browser_result.spec.js
test/unit/cli.spec.js
test/unit/completion.spec.js
test/unit/config.spec.js
test/unit/emitter_wrapper.spec.js

So this is another take on migrating code base to ES2015 classes, const/let and arrow functions. With Node 4 [reaching](https://github.com/nodejs/Release#release-schedule) end-of-life in 2 months developers soon can enjoy [full support](https://kangax.github.io/compat-table/es6/#node6_5) of ES2015 :smile:
Using mentioned syntaxes should give cleaner, more structured and therefore more maintainable code.
I originally tried to base my work on https://github.com/karma-runner/karma/pull/2904 from @EzraBrooks, but rebasing on master turned out to be very nasty, so I gave up and started over.
The goal of this PR is exclusively migration to ES2015 and NOT change of a DI mechanism. I monkey-patched `di` module to support ES classes for now. Everything should work exactly the same as it worked for …

Migrate to ES2015

---

docs/intro/03-how-it-works.md

This short narative also helps introduce 'client' and 'context' terminology.

docs: Outline the basic workflow.

---

appveyor.yml
lib/server.js
test/unit/middleware/proxy.spec.js
test/unit/server.spec.js

Not removing Socket.IO listeners can cause memory issues
in long running processes that spawn many Karma instance.
Fixes #2980

fix(server): Remove Socket.IO listeners

---

lib/watcher.js

This pull request simplify a bit logic in `watcher.js` method.

refactor(watcher): refactor watcher.js

---

lib/events.js
lib/launchers/base.js
lib/server.js
test/unit/events.spec.js

Within this pull request I moved lib/events into ES6 class. In next iteration I'm planning to migrate pseudo-classes that extends `KarmaEventEmitter` into classes.

refactor: migrate lib/events.js into ES6

---

lib/reporters/base.js
test/unit/reporters/base.spec.js

Converted to ES2015 syntax and re-arranged code a bit, so conversation to real class won't produce hard to review diff.
In tests import BaseReporter directly instead of using `mocks`. This was unnecessary complexity.

Prepare BaseReporter for conversion to class

---

common/stringify.js
test/client/stringify.spec.js

There were problems with using console.log while running test that resulted in errors like:
```
Chrome 66.0.3359 (Windows 7.0.0) moves should move rock box player up if they are adjacent one over each other FAILED
TypeError: Cannot convert a Symbol value to a string
at <Jasmine>
at ContextKarma.stringify (http://localhost:9876/context.js:1804:34) // here stringify
at ContextKarma.log (http://localhost:9876/context.js:1867:24)
at <Jasmine>
at Algorithm.resolveCell (src/game-00/main.test.ts:214654:13)
at ordered.filter.obj (src/game-00/main.test.ts:214613:42)
at <Jasmine>
at Algorithm.update (src/game-00/main.test.ts:214613:23)
at UserContext.it (src/game-00/main.test.ts:214494:19)
```
or
```
TypeError: Cannot convert a Symbol value to a string
at ContextKarma.stringify (context.js:75:34) …
```

fix: stringify error on 'Cannot convert a Symbol value to a string'

---

.eslintrc
lib/config.js
lib/init.js
lib/launcher.js
lib/logger.js
lib/reporter.js
lib/server.js
lib/watcher.js
package.json
test/unit/preprocessor.spec.js
test/unit/server.spec.js

This pull request updates eslint configuration a bit, main changes:
- add `space-before-function-paren` rule to prevent code style changes like [here](https://github.com/karma-runner/karma/pull/2973/files#r190820886)
- I noticed that files `lib/*.js` was not linted by previous configuration, so I updated `npm run lint` script, and fixed a few lint issues
- added `npm run lint:fix` script to make it easier to fix things by developer on localhost

refactor: update eslint configuration

---

lib/launcher.js
test/unit/launcher.spec.js

Within this pull request I've used a few ES6 features in `lib/launcher.js` file to improve it's readability.

refactor(launcher): Update launcher to ES6

---

.eslintignore
.gitignore
lib/server.js
lib/utils/bundle-utils.js
lib/utils/file-utils.js
lib/utils/path-utils.js
test/unit/server.spec.js
test/unit/utils/bundle-utils.spec.js
test/unit/utils/path-utils.spec.js

Pull request refactor code around `static/context.js` and `static/karma.js` bundling. Main changes:
- move code responsible for bundle resources with `browserify` into `lib/utils/bundle-utils`
- move responsibility to check if bundled files exists into `BundleUtils.bundleResourceIfNotExist` method
- overall refactoring
- adding unit tests for created methods

refactor(server): refactor bundleResource in lib/server.js

---

lib/server.js

Many problems in karma use can be resolved by reading the config, but plugins can mutate the config.
Here debug logging will give the final result after any mutations.

fix(config): Log the final config just before use.

---

lib/server.js
lib/utils/net-utils.js
test/unit/server.spec.js
test/unit/utils/net-utils.spec.js

- create NetUtils with `isPortAvailable` and `getAvailablePort` methods
- use NetUtils to search for available port before starting server and build middlewares
- remove handler for `EADDRINUSE` error - with `NetUtils.getAvailablePort` we'll know that port is available for sure, so this error would no raise

fix: check for available port before start server (fix #1476, fix #3011)

---

lib/reporters/base.js
test/unit/reporters/base.spec.js

Fix an issue that when the run completes with just one browser, the log message is missing.

fix(BaseReporter): log message correctly with just one browser

---

lib/server.js
lib/web-server.js
test/unit/web-server.spec.js

By removing the creation of file-service handlers from the webserver, we create functions with better 
focus and we allow the file-service handlers to be used in beforeMiddlewaare. The only cost is that these objects are now visible to all modules rather than being private to webserver. The potential for collision seems small.

refactor(server): Provide file-service handlers in the root injector.

---

lib/launcher.js
test/unit/launcher.spec.js

This is a regression in 2.0.3: if karma server is started and a users browser attached, the launch throws

fix(launcher): Only markCaptured browsers that are launched.

---

lib/events.js
test/unit/events.spec.js

fix(events): bind emitters with for..in.

---

lib/server.js
test/unit/server.spec.js

fix(server): Resurrect static function Server.start() lost in 2.0.3

---

lib/server.js
test/unit/server.spec.js

Warn that the function without a test will be removed.
Fixes #3061 by @GreenGremlin

fix(server): actually call start().

---

lib/preprocessor.js
test/unit/preprocessor.spec.js

Karma currently detects whether a file is binary, and does not allow binary files to be passed on to preprocessors. This PR removes this restriction, and allows binary files to be handled by preprocessors.
See https://github.com/karma-runner/karma/issues/3046

feat(preprocessor): Allow preprocessor to handle binary files

---

lib/server.js
lib/utils/net-utils.js
package.json
test/unit/server.spec.js
test/unit/utils/net-utils.spec.js

Fixed #3065 by passing `handle` that has already been bound to a port, see [server.listen](https://nodejs.org/api/net.html#net_server_listen_handle_backlog_callback).

Fixed `EADDRINUSE` issue for tests running in parallel

---

lib/browser.js
test/unit/browser.spec.js

After migrating the the `browser.js` file to ES2015, the `Browser` class has now fields with circular references (like `emitter`), which breaks the Karma JSON reporters available starting with Karma 2.0.1.
This commit removes the circular dependencies by adding a `toJSON()` method to the `Browser` class, which produces a similar result to the browser object before the migration.
Fixes #3075

fix: remove circular reference in Browser

---

lib/middleware/common.js

Rather than catching and discarding the error if no error handler is passed, let the promise package chain it. This allows use to have a .catch() follow the then().

fix(middleware): Obey the Promise API.

---

client/updater.js
lib/browser.js
lib/browser_collection.js
lib/executor.js
lib/reporters/base.js
test/unit/browser.spec.js
test/unit/browser_collection.spec.js

Browser state is EXECUTING when it actually started to execute tests. This state change is triggered by client on actual tests execution start.
Fixes https://github.com/karma-runner/karma/issues/1640

fix(browser): ensure browser state is EXECUTING when tests start

---

docs/config/01-configuration-file.md
lib/config.js

https://docs.travis-ci.com/user/gui-and-headless-browsers/#karma-and-firefox-inactivity-timeouts

fix(config): Wait 30s for browser activity per Travis.

---

lib/completion.js
lib/init.js

We can add `ChromeHeadless` in the options for `browsers` when using `karma init`

fix(init): add "ChromeHeadless" to the browsers' options for "init" command

---

lib/middleware/karma.js
lib/server.js

Add a handler for unhandledRejections, log error and disconnect all, then exit.
Also remove broken, untested rejection handler in middleware. Prior to #3064,
this block was probably unreachable; the arguments to serveStaticFile are incorrect.

fix(server): Exit clean on unhandledRejections.

---

CHANGELOG.md

* update breaking change(drop node4 support) for Karma v3 in changelog

[Docs] Update BREAKING CHANGES in CHANGELOG

---

lib/init.js

Looks like this was missed in #3096.

fix(init): Support ChromeHeadless in `validateBrowser`

---

lib/helper.js
lib/middleware/runner.js
test/unit/helper.spec.js
test/unit/middleware/runner.spec.js

fix(runner): Do not persist grep option across runs

---

docs/dev/05-plugins.md
lib/file.js
lib/middleware/source_files.js
test/unit/middleware/source_files.spec.js

This change allows preprocessors to specify an encoding for files. Currently, if a preprocessor encodes a file in a format such as gzip or Brotli, the file is served with the wrong encoding. The only workaround for this is to also include a plugin ([example](https://github.com/GreenGremlin/karma-gzip/blob/master/lib/Plugin.js)) that removes encoded files from `files.served` and serves them manually using a custom file handler. This approach is a gross hack that unnecessarily complicates the encoding plugin's logic.
With this change, a preprocessor encodes the contents and stores them in the File class' new `encodings` property. The `encodings` property is a keyed object where the keys are the encoding type ('gzip', 'compress', 'br', etc.) and the values are the encoded content. This …

feat(server): Add support for encoded source files

---

lib/middleware/karma.js
lib/middleware/strip_host.js
lib/web-server.js
test/unit/middleware/strip_host.spec.js

The stripHost middleware only adds a modified url to the request.
That modified url is only used one place. By converting the middleware
to a module, the code is simpler and beforeMiddleware modules can reuse
karma middleware. (One alternative considered was to move the stripHost
in the chain before the beforeMiddleware, but this form seems better).
Clean up regex per offline suggestion from zzo@

fix(middleware): simplify stripHost.

---

docs/config/01-configuration-file.md

Superseeds https://github.com/karma-runner/karma/pull/3139

docs(config): customized typeScript configuration

---

lib/launchers/base.js

This pull request is the first step that should help us to transform `BaseLauncher` to be ES6 class

refactor(launcher): use this directly instead assign to self variable in base launcher

---

test/client/karma.conf.js
test/client/karma.spec.js
test/client/mocks.js
test/client/stringify.spec.js
test/client/util.spec.js

We still test in IE9/10 where the `var` is king.

fix(test/client): revert const/let changes.

---

context/karma.js
test/client/karma.spec.js

Sometimes native console methods are broken, but this shouldn't break tests.
It is especially undesirable in environments like Sauce Labs with limited access to the browser settings.
See https://github.com/angular/angular.js/pull/16644#issuecomment-407680658

fix: work around broken console methods

---

lib/server.js
test/unit/server.spec.js

feat(server): Add stop method

---

docs/dev/04-public-api.md
lib/file-list.js
lib/server.js
test/unit/file-list.spec.js

Adds a public API similar to `server.refreshFiles()` that allows to refresh a specific file.
This is useful for preprocessors that process files with dependencies (sass, js modules, postcss), so they can trigger an update on a file when a change is detected on a dependency.
Contrary to `server.refreshFiles()` it allows to refresh only the file that need to be processed again.

feat(server): Add public API to force a file refresh

---

static/context.html
static/debug.html
test/e2e/module-types.feature
test/e2e/support/modules/__tests__/minus.test.mjs
test/e2e/support/modules/__tests__/plus.test.js
test/e2e/support/modules/minus.mjs
test/e2e/support/modules/plus.js
test/e2e/support/modules/test.js

PR is intended to check build status of #2834. This is the same one but rebased off the current HEAD.

Add tests for ES2015 module support 

---

lib/browser.js

BrowsersCollection.add emit `browsers_change` event, so there is no need to emit it once again from Browser instance.

fix(browser): emit 'browsers_change' in collection

---

lib/cli.js
lib/config.js
test/unit/cli.spec.js

NodeJS includes [assertion library](https://nodejs.org/api/assert.html) natively, and it's syntax seems to be more elegant that throwing errors directly.

refactor(lib): use assert library instead of throwing error directly

---

package.json
test/unit/helper.spec.js

Bump `useragent` to `2.3.0` to pull in ua-parser/uap-core#263 in which Headless Chrome version detected to be `0.0.0`.
Update tests to reflect latest `useragent` OS major version string identifiers.
Per https://github.com/ua-parser/uap-core/pull/286 , `useragent` purposely sets the Windows Vista `family` to `Windows` and `major` version to `Vista`. The change to `useragent` was intentional, and the maintainer advises upstream consumers to update tests to reflect the change.
Per https://github.com/3rd-Eden/useragent/issues/120 , there is an open question to change the stringified OS to not include `0` for missing version numbers. For example:
```
family: 'Windows'
major: 'Vista'
minor:
patch:
patch_minor:
```
would display as `"Windows Vista"` instead of `"Windows Vista.0.0"`.
That open …

fix(dep): Bump useragent to fix HeadlessChrome version

---

lib/browser.js

refactor(browser): log state transitions in debug

---

package.json

Bumps lodash to 4.17.5 avoid medium severity vulnerability (https://nvd.nist.gov/vuln/detail/CVE-2018-3721) found in 4.17.4.
Closes #3177.

fix(package): bump lodash version

---

lib/file-list.js
test/unit/file-list.spec.js

It improves performance of "karma run" command which refreshes fileList.
Closes #2829

fix(file-list): do not preprocess up-to-date files

---

lib/browser.js
test/e2e/browser_console.feature
test/e2e/error.feature
test/e2e/step_definitions/core_steps.js
test/unit/browser.spec.js

fix(browser): report errors to console during singleRun=false

---

lib/file-list.js
test/unit/file-list.spec.js

This reverts commit 5334d1a8
karma-webpack preprocessor updates bundle when needed, but karma's fileList consists of a single entry file which is usually unmodified. In this case, fileList.refresh() should always call preprocessor for the single entry file, avoiding preprocessing of unmodified files is done on karma-webpack side.

fix(file-list): revert "do not preprocess up-to-date files" (#3226)

---

lib/launchers/process.js
test/unit/launchers/process.spec.js

Fixes karma-runner/karma-chrome-launcher#181

fix: improve error msg when bin is a directory

---

client/karma.js
lib/browser.js
lib/server.js
test/client/karma.spec.js
test/unit/browser.spec.js
test/unit/server.spec.js
yarn.lock

Currently whenever a browser disconnects completely (no socket.io connection loss), the launcher is instructed to `"restart"` the browser. 
Whenever the restarted browser now tries to `"register"` again, Karma considers the browser instance to be still executing and doesn't do anything about it (except setting the state from `EXECUTING_DISCONNECTED` to `EXECUTING` again).
This means that the browser is in the state of executing, but practically it **does nothing** and just waits. 
*Resulting in another disconnect (story repeats here)*

fix: restarted browsers not running tests

---

.travis.yml
appveyor.yml
docs/intro/04-faq.md
package.json

This pull request remove support for node v6.
Let me know if I missed something here ...

chore: remove support for node 6

---

context/karma.js
test/client/karma.spec.js

fix(client): fix issue with loaded on safari 10
Safari 10 supports type=module but ignores nomodule which causes loaded() to execute twice.
Fixes #3198

fix(client): fix issue with loaded on safari 10

---

lib/browser.js
test/unit/browser.spec.js

This change allows providing the total specs count after the tests have
been started.
The count will be updated in case it has been provided already.
This can be uselful for some adapters where the total specs count can
not be determined before starting the first test.
**Regarding tests**
I wanted to update the tests and/or create a test case but the `onInfo` tests are not clear to me:
- 'browser_dump' doesn't seem to be a valid event
- I'm not sure whether the behavior of the tests is really expected or just works by chance.
So I would be happy to get feedback from you before writing a test case.
https://github.com/karma-runner/karma/blob/c277a6bd130531702e2529f0410aa441328f187e/test/unit/browser.spec.js#L102-L137

fix(browser): allow updating total specs count

---

lib/watcher.js
package.json

Remove `expand-braces` as a dependency. Use `braces.expand` instead
now.
Fixes #3268
Fixes #3269
Check that your description matches the automatic change-log format:
http://karma-runner.github.io/latest/dev/git-commit-msg.html
then delete this reminder.

fix: remove vulnerable dependency expand-braces

---

lib/browser.js
lib/file-list.js

Append the state of the browser if it gets lost.

fix(filelist): correct logger name.

---

lib/launchers/base.js

fix(launcher): Log state transitions in debug

---

client/karma.js
lib/middleware/karma.js

Enable loading different file types when running in parent mode without iframe.
By default, the Karma middleware reads the included files and generates the corresponding HTML in string which eventually replaced the %SCRIPTS%. The client then later loads the iframe that embeds this context.html.
In #2542, I introduced a third option to run tests on lightweight browsers without iframe support. This is achieved by running test within the parent page and dynamically load all the files. I created a client_with_context.html which combines both client.html and context.html. The Karma middleware will concatenate all the included file paths, turns it to a long string with ',' separator and replace it with %SCRIPT_URL_ARRAY% in client_with_context.html. On the client side, it will read the …

fix(client): Enable loading different file types when running in parent mode without iframe

---

client/karma.js

fix(client): Only create the funky object if message is not a string

---

lib/watcher.js
package.json
yarn.lock

This results in a significant dependencies reduction from [braces refactor](https://github.com/micromatch/braces/blob/master/CHANGELOG.md#300---2018-04-08). New version of chokidar also promises significant memory and CPU usage [improvements](https://github.com/paulmillr/chokidar/releases/tag/3.0.0).

chore: update braces and chokidar to latest versions

---

test/e2e/error.feature
test/e2e/step_definitions/core_steps.js
test/e2e/stop.feature
test/e2e/support/reconnecting/test.js

See separate commits for details on fixed issues.

chore(test): fix flaky test cases

---

package.json
yarn.lock

Mocha 5+ dropped support for IE 8 and IE 9. This leads to [failing
BrowserStack tests](https://travis-ci.org/karma-runner/karma/jobs/534037781#L900), so reverting back to version 4 until Karma decides
to drop support for the mentioned browsers.

chore: revert back to Mocha 4

---

lib/reporter.js
test/unit/reporter.spec.js

Columns in original stack are 1-based, but
SourceMapConsumer.prototype.originalPositionFor(generatedPosition)
accepts 0-based column and returns 0-based column too.
This change converts columns from 1-based to 0-based forth and back.
Closes #3324

fix(reporter): format stack with 1-based column

---

lib/server.js

While flatten is accurate and works with circular data, it's too hard to read.
By using vanilla json for most cases the log will be clearer.

fix(logging): Use flatten only if config is circular.

---

lib/server.js
test/unit/server.spec.js

feat(async): frameworks can be loaded asynchronously

---

package.json
yarn.lock

The resulting yarn.lock no longer depends on natives.

chore(deps): npm install karma-browserstack-launcher

---

tasks/test.js
test/e2e/error.feature

It is not enough to check exit `code`, because when process crashes `code` is set to `null` and `err` is passed instead. Adjusted build script accordingly and forced new version of `natives` to make tests pass.
Example of failing tests, which didn't fail build:
https://travis-ci.org/karma-runner/karma/jobs/537027667#L1046

fix(test): `test:client` silently failing on Travis

---

docs/dev/04-public-api.md
lib/cli.js
lib/runner.js

This might be the case when Karma.run() is called inside the same
process/terminal as the server is running in (e.g. development
servers).
Fixes #2121, #2799

feat(runner): Config option to prevent logging to the console twice

---

docs/config/04-preprocessors.md
lib/config.js
lib/preprocessor.js
lib/server.js
test/unit/preprocessor.spec.js

Between 3.x and 4.x we moved from combineLists to underscore.union in preprocessor.
Apparently combineLists was incorrect: the order of preprocessing changed in some cases.
Conceptually the order ought to depend upon the preprocessor, not the file.
Implement config.preprocessor_priority['preprocessor-name'] = priority, higher means run earlier.
Default priority is 0.
Check that your description matches the automatic change-log format:
http://karma-runner.github.io/latest/dev/git-commit-msg.html
then delete this reminder.

feat(preprocessor): preprocessor_priority execution order.

---

docs/config/01-configuration-file.md
lib/config.js
lib/server.js
test/unit/config.spec.js

feat(config): socket.io server pingTimeout config option.

---

client/karma.js
client/updater.js

With this change, Karma tests can be run with an enforced Trusted Types policy.
This change consists of using safer APIs (appendChild and textContent instead of innerHTML), as well as creating a policy for client/karma.js which a test's Trusted Types CSP policy can then explicitly allow. This policy is used internally where karma does potentially dangerous operations like loading scripts.
More info about the proposed Trusted Types standard at https://github.com/WICG/trusted-types

feat(client): Add trusted types support

---

client/karma.js
client/main.js
docs/config/01-configuration-file.md
test/client/karma.spec.js

When karma is used for compontent testing with screenshots, the client elements make screenshot comparison
more difficult.  config.client.clientDisplayNone will set the element style to display.none.

feat(config): clientDisplayNone sets client elements display none.

---

.travis.yml

Since of May 2019 by default start Ubuntu Xenial 16.04
https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
and also since Ubuntu 16.04 you can start xvfb as services
https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui

chore: travis - upgrade on new version Ubuntu 16.04

---

lib/browser.js
test/unit/browser.spec.js

There are failOnFailingTestSuite and failOnEmptyTestSuite, so in this there is no necessity
Fixes #3367

fix(runner): remove explicit error on all tests failed

---

lib/preprocessor.js

Similar that mocha support like you can execute done or return Promise

feat: Preprocessor can return Promise

---

client/main.js
common/stringify.js
package-lock.json
package.json
test/client/karma.spec.js

The core-js was used for dom-serialize, used to support a single function
in stringify (serialize) for a single rare browser, IE8, in logs sent back to
the server.  By dropping this dependency we reduce the size of karma with
minimal impact on use cases.

feat(deps): Remove core-js dependency.

---

docs/config/01-configuration-file.md
lib/browser_collection.js
test/unit/browser_collection.spec.js

Recently jasmine added support for reporting pending (incl due to fit()) tests.
These appear in results as skipped tests and this failOnPendingTests option allows us to fail tests
with skipped tests.

feat(config): add failOnSkippedTests option.

---

lib/browser_collection.js
lib/server.js
test/unit/browser_collection.spec.js
test/unit/server.spec.js

Fix async test structure. 
Correct logic of failOnEmptyTestSuite.
Incorporates the fix in PR #3381 by ilgonmic

fix(server): Add test coverage for config.singleRun true branch.

---

package.json
test/client/karma.conf.js

Return to v1.5 karma-browserstack-launcher

fix(ci): poll every 10s to avoid rate limit.

---

lib/file-list.js
lib/preprocessor.js
package-lock.json
package.json
test/unit/file-list.spec.js
test/unit/preprocessor.spec.js

update isbinaryfile on async  version

refactor: make the preprocesor as full async method

---

test/client/karma.conf.js

I've hit this a couple of times but many months apart, enough time to forget. The error is quite
puzzling without some hints.
Fixes #3391

test(config): Check for the correct symbolic link before test:client

---

lib/server.js

Add a log for receiving errors from the karma-server instead of UncaughtException/UncaughtRejected
Fixes #3342

feat(karma-server): added log to the server.js for uncaught exceptions

---

lib/executor.js
lib/middleware/runner.js
test/unit/executor.spec.js
test/unit/middleware/runner.spec.js

This PR adds error handling for rejections on the file list methods in the runner middleware. As discussed in #3396 it does this by handling an error the same way an error in a run is handled.
Fixes #3396

fix(middleware/runner): handle file list rejections

---

test/unit/file-list.spec.js

5 years ago someone set the test file time to 2020. And here we are.

chore(tests): advance the future time by 1000 yrs

---

lib/server.js

Display original error message of plugins like: 
* [karma-browserstack-launcher](https://github.com/karma-runner/karma-browserstack-launcher)
* [karma-cbt-launcher](https://github.com/karma-runner/karma-cbt-launcher)
Fixes #3414

fix(server): Report original error message

---

test/e2e/step_definitions/core_steps.js
test/e2e/upstream-proxy.feature

The test fails flaky but we don't have hints. Now a failing test should dump the
debug text.

chore(test): logLevel debug in proxy test

---

lib/config.js
lib/file-list.js
lib/file.js
lib/preprocessor.js
test/unit/preprocessor.spec.js

Add support for isBinary. If set, use it and don't probe file to detect binary status.
Fixes #3405

feat(preprocessor): obey Pattern.isBinary when set

---

.travis.yml
appveyor.yml
package.json

BREAKING CHANGE: no more testing on node 8.

ci: drop node 8, adopt node 12

---

docs/dev/04-public-api.md

This docs update was missing in the #2479 that added option for configurable
listening address.
Thanks!

feat(docs): document `DEFAULT_LISTEN_ADDR` constant

---

lib/preprocessor.js
package-lock.json
package.json

BREAKING CHANGE: Deprecated createPreprocessor removed, karma-browserify < 7 version doesn't work

fix(server): createPreprocessor was removed

---

lib/server.js

This is a leftover from 5f13e11784c283872c97501b9e21402987429c56.

fix(server): cleanup import of the removed method

---

lib/middleware/common.js
package-lock.json
package.json

This library is a polyfill for Buffer's static methods on ancient Node versions (new methods are available since [at least Node 4](https://nodejs.org/docs/latest-v4.x/api/buffer.html)). No reason to have this polyfill given that Karma support Node 10+.
When these methods are supported natively library exports native `Buffer` ([code](https://github.com/feross/safe-buffer/blob/master/index.js#L11)), so this removal should not affect anything.

refactor: drop safe-buffer dependency in favor of native Buffer

---

lib/file-list.js
lib/helper.js
lib/launcher.js
lib/launchers/base.js
lib/server.js
lib/utils/bundle-utils.js
lib/utils/net-utils.js
package-lock.json
package.json
test/.eslintrc
test/unit/file-list.spec.js
test/unit/launcher.spec.js
test/unit/launchers/base.spec.js
test/unit/launchers/capture_timeout.spec.js
test/unit/launchers/process.spec.js
test/unit/middleware/runner.spec.js
test/unit/mocha-globals.js
test/unit/utils/net-utils.spec.js

All supported Node versions support native promises and async/await, current code has a minimal usage of Bluebird-specific methods, so dropping a third-party library in favor of native Promises.
Tests were using `Promise.setScheduler()` from Bluebird, which allowed to customize how Promises are scheduled and made test work very different from the real code, which created tricky issues (like https://github.com/karma-runner/karma/pull/3060#discussion_r284797390). Affected tests were updated to not rely on `Promise.setScheduler()`, which improved readability in some situations. Also removed some test helpers as they are not necessary and not used anymore.
The only drawback I can think of is that Bluebird potentially provides better stack traces for async calls, which are only supported in …

refactor: use native Promise instead of Bluebird

---

lib/helper.js
package-lock.json
package.json
test/e2e/basic.feature
test/e2e/browser_console.feature
test/e2e/custom-context.feature
test/e2e/files.feature
test/e2e/headers.feature
test/e2e/middleware.feature
test/e2e/proxy.feature
test/e2e/reconnecting.feature
test/e2e/runInParent.feature
test/e2e/upstream-proxy.feature
test/unit/browser.spec.js
test/unit/helper.spec.js

BREAKING CHANGES - Browser and OS name generation are changed
swich on new lib ua-parser-js to have a good detection of MS Edge Chromium

fix(server): detection new MS Edge Chromium

---

context/karma.js
docs/config/01-configuration-file.md
test/unit/config.spec.js

There is a small typo in context/karma.js, docs/config/01-configuration-file.md, test/unit/config.spec.js.
Should read `overridden` rather than `overriden`.

docs: Fix simple typo, overriden -> overridden

---

.travis.yml
package-lock.json
package.json

Also changed global executable to NPM script as global executable will not be available unless the package is installed globally (with `npm i -g`).

fix: install semantic-release as a regular dev dependency

---

lib/file-list.js
test/unit/file-list.spec.js

Defining fs.statAsync affects other modules such as bluebird which
throws an error because of the 'Async'-suffix:
> Cannot promisify an API that has normal methods with 'Async'-suffix
> See http://goo.gl/MqrFmX
Fixes: https://github.com/karma-runner/karma/issues/3466

fix(file-list): do not define fs.statAsync

---

cucumber.js
test/e2e/basic.feature
test/e2e/runInParent.feature
test/e2e/tag.feature

This tag was useful long time ago, when most of the tests were run using PhantomJS. For a long time E2E tests use ChromeHeadless as a the main browser and it is not needed to mark tests using Google Chrome to only run locally. Two removed test cases have identical cases above them, which are run in the ChromeHeadless and other two were updated to run in ChromeHeadless instead of Chrome and will be run both in CI as well as locally.

chore(test): remove @not-jenkins tag for Cucumber tests

---

test/client/karma.conf.js

https://github.com/karma-runner/karma-browserstack-launcher/issues/61
Fixes #3468

chore(ci): use recommended timeouts for browserstack

---

.travis.yml

- Fix warnings reported by Travis (https://travis-ci.org/github/karma-runner/karma/builds/677410665/config).
- Remove installation of g++-4.8 as it is no longer needed.
- Remove SAUCE_USERNAME variable as it is configured in the Travis UI now.
- Remove fast_finish as it only makes sense when some jobs are allowed to fail (https://docs.travis-ci.com/user/build-matrix/#fast-finishing). Which is not the case.

chore(ci): cleanup Travis config

---

.travis.yml
package.json

Assuming that the issue is concurrent jobs attempting to interact with BrowserStack using the same build ID, this solution attempts to solve it by only interacting with BrowserStack in one of the jobs.
Updated build definition:
- runs complete build on the latest Node
- runs simplified build (without commit validation, lint, test:client and test:integration) on earlier versions on Node
It is not very valuable to run omitted test suits multiple times as they supposed to catch issues, which are usually Node-independent: client code fails in some browsers and API breaking changes, which will affect popular Karma plugins.
Fixes #3468

chore(ci): fix BrowserStack timeouts

---

client/karma.js

fix(client): flush resultsBuffer on engine upgrade

---

test/e2e/reporting.feature
test/e2e/support/reporting/test.js

A test case to catch https://github.com/karma-runner/karma/pull/3212 regressions. It fails now, but will pass once the other PR is merged and test is rebased.

chore(test): add test for flush resultsBuffer on engine upgrade

---

lib/browser.js

Otherwise empty array is treated as a single value, which causes issues down the road.

fix(browser): make sure that empty results array is still recognized

---

test/e2e/support/proxy.js
test/e2e/support/world.js

We used to share single instance of this class between all scenarios, but this is not necessary as each scenario starts proxy on demand and stops it in [After hook](https://github.com/karma-runner/karma/blob/master/test/e2e/step_definitions/hooks.js#L7). It should be cleaner to have an independent instance for each scenario.

refactor(test): migrate Proxy to ES2015

---

test/e2e/step_definitions/core_steps.js
test/e2e/step_definitions/hooks.js
test/e2e/support/proxy.js
test/e2e/upstream-proxy.feature

First step to simplify execKarma method, which is overcomplicated and has too many responsibilities.

refactor(test): extract proxy into a separate Given claim

---

.eslintignore
.gitignore
test/e2e/browser_console.feature
test/e2e/launcher-error.feature
test/e2e/step_definitions/core_steps.js
test/e2e/step_definitions/hooks.js
test/e2e/support/world.js
test/e2e/timeout.feature

This is a bit bigger change, but modifications are related and I think it makes sense to land them all together.
The main change is in test/e2e/support/world.js file, where all important paths are defined:
- `workDir` is the current working directory for the tested Karma process - `test/e2e/support`. Same as before.
- `sandboxDir` moved from `tmp/sandbox` in the repository root to `test/e2e/support/sandbox`. Sandbox directory is reset before every scenario (see `test/e2e/step_definitions/hooks.js`) and this is where all generated files should be (hence change of paths in `browser_console.feature`). This also makes things cleaner as now all paths in the .feature files are relative to `workDir`.
- `configFile` is path where Karma config file is generated. It no longer contains hash as it …

refactor(test): adjust sandbox folder location and simplify config logic

---

test/e2e/step_definitions/core_steps.js
test/e2e/stop.feature

From the description of the steps it makes sense to write it straight away. Also this is more flexible and allows to introduce steps, which do not require config file in the future PR.

refactor(test): write config file in its own steps

---

test/e2e/browser_console.feature
test/e2e/error.feature
test/e2e/launcher-error.feature
test/e2e/pass-opts.feature
test/e2e/step_definitions/core_steps.js
test/e2e/step_definitions/hooks.js
test/e2e/support/world.js
test/e2e/timeout.feature

The existing code had pretty confusing logic (old lines 33-36): when background server start fails it is actually considered a success, but child process is not started. Because of this `lastRun` contains result output of the `karma start`. This is no longer the case, hence two test cases had to be updated as they never executed `karma run` despite the statement and were asserting against `karma start` output. This should be more clear now.
As background server process now has its own variable to store output, there is no need for a dedicated runOut command and it can be removed.

refactor(test): add common method to start server in background

---

test/e2e/browser_console.feature
test/e2e/error.feature
test/e2e/pass-opts.feature
test/e2e/step_definitions/core_steps.js
test/e2e/step_definitions/utils.js

Finally!
Introduced extra step "I wait until server output contains" instead of hard-coded timeout. It will regularly evaluate a condition until it fulfills. This approach should potentially perform a little bit better than the previous solution.

refactor(test): reduce execKarma to a reasonable size

---

test/e2e/pass-opts.feature
test/e2e/step_definitions/core_steps.js
test/e2e/stop.feature
test/e2e/support/world.js
test/e2e/upstream-proxy.feature

Also generalize a step to accept any CLI arguments instead of only log-level. This should make this step more flexible. After the recent changes the removed step was not very clear as to which command (foreground or background) it applies to and is fully covered with expanded "I {command} Karma ..." step.

refactor(test): move execKarma into the World

---

lib/cli.js
test/e2e/cli.feature
test/e2e/step_definitions/core_steps.js

These were lost after migration to `yargs` as CLI parser.
The only issue I've noticed is that `yargs` reports all unknown arguments in the error about unknown command, but I guess we can live with it for now:
```bash
$ karma bla bla bla
...
Unknown commands: bla, bla, bla
```
Fixes #3474

fix(cli): restore command line help contents

---

test/e2e/pass-opts.feature
test/e2e/step_definitions/core_steps.js

There is no need to filter out [DEBUG] logs as tests are run with logLevel = "warn" by default.

refactor(test): remove no debug matching option

---

CHANGELOG.md

I'm trying to update a Markdown parser for the documentation website and it fails on this broken markup.

chore: fix broken HTML markup in the changelog file

---

docs/dev/05-plugins.md
lib/file.js
lib/middleware/karma.js
lib/url.js
test/e2e/helpful-logs.feature
test/unit/file.spec.js
test/unit/url.spec.js

fix: detect type for URLs with query parameter or fragment identifier

---

package-lock.json
package.json

It was locked in 73e300da116540a0b63b4f34a4f9dfb74606b0a7 to fix support of ancient IE versions, which is no longer relevant.

fix(dependencies): update and unlock socket.io dependency

---

gruntfile.js
package-lock.json
package.json

chore: remove unused `grunt lint` command

---

test/e2e/step_definitions/core_steps.js
test/e2e/step_definitions/utils.js

Also added a custom error logic, so actual output is printed if condition times out.
Example https://travis-ci.org/github/karma-runner/karma/jobs/688421469#L643

chore: increase step timeout to prevent flakiness

---

.npmignore
release.config.js
tools/update-docs.js

This will automatically update the documentation after publishing a new release.
Example: https://github.com/devoto13/karma-runner.github.com/commits/master
I don't have a way to test it on Travis before merging... But it works locally. So as long as `GH_TOKEN` with push access to https://github.com/karma-runner/karma-runner.github.com is available and Travis does not do anything funny with the temporary directory handing this should work on Travis as well.

ci: update documentation after publishing a release

---

lib/middleware/proxy.js
test/unit/middleware/proxy.spec.js

Using an agent with keepAlive improves performance as the socket is
reused across multiple requests.

fix(proxy): use keepAlive agent

---

lib/server.js

When these differ the hostname is clearer.

fix(server): echo the hostname rather than listenAddress

---

lib/server.js
test/unit/server.spec.js

Previously the error has been fully ignored.
This has been detected within [SAP/openui5](https://github.com/SAP/openui5) where we start a local server in parallel to karma. When upgrading to karma v5 we faced some issues mainly on Windows. It turned out that the root cause is `EMFILE, too many open files`, probably because internal timings have changed by switching from bluebird to native Promises.
As the actual error hasn't been logged, it took me some time to find out where the error comes from.
We solved the problem on our side by starting the server as part of an async framework plugin, instead of just `require`ing it from the `karma.conf.js` (see https://github.com/SAP/openui5/commit/e77a49a64d3fed1da65689b1f8eb1674297f6602). This ensures that it doesn't get executed while karma is …

fix(server): log error when file loading or preprocessing fails

---

client/karma.js
static/karma.js
test/client/karma.spec.js

Add a delay in execute to ensure that reload events and clear context events are completed first.
Fixes #3424

fix(client): avoid race between execute and clearContext

---

lib/server.js
test/unit/server.spec.js

Currently it seems that it's not possible for reporters to set the exit code asynchronously.
Within the "onRunComplete" event, the `results.exitCode` must be modified synchronously, otherwise the updated value is not taken into account.
With this change, the reporters (or any other plugin) can pass an exit code to the callback of the 'exit' event.
This is the only existing place I've found to be leveraged without creating a lot of new code and APIs.
This is currently a problem in the `karma-coverage` plugin.
See https://github.com/karma-runner/karma-coverage/issues/418 and https://github.com/matz3/issue-karma-coverage-threshold-exit-code

feat(server): allow 'exit' listeners to set exit code

---

package-lock.json
package.json

By locking sinon to the older version. The problem was that new version of sinon brought newer versions of several dependencies, which use ES2016 Map, which is not available in the older IE versions. The solution is fragile as we can't reliably lock transitive dependencies, but should do for now to make master green.
As a proper solution we should consider cutting a new major release, where we would drop support for ancient browsers and more clearly document which browsers karma aims to support.

chore(test): fix client tests in older IE versions

---

tools/update-docs.js

The task has never succeeded because there was a typo in the repository URL.
See https://travis-ci.org/github/karma-runner/karma/jobs/722815882#L1324
But build has never failed either, because "The exit code of after_success, after_failure, after_script, after_deploy and subsequent stages do not affect the build result." according to Travis [documentation](https://docs.travis-ci.com/user/job-lifecycle/#breaking-the-build) and this code was run in `after_success` stage. This should be fixed in a separate PR though.

chore(release): fix documentation update task

---

docs/plus/06-angularjs.md

The link [Full Spectrum Testing with AngularJS and Karma](http://www.yearofmoo.com/2013/01/full-spectrum-testing-with-angularjs-and-karma.html) is no longer working, http://www.yearofmoo.com cannot be reached.

fix: remove broken link from docs - 06-angularjs.md

---

lib/reporters/base_color.js

This change switches use of the `color` module for `color/safe` to avoid mutating the shared primordials. Tools like [SES](https://github.com/Agoric/SES-shim/tree/master/packages/ses) make the primordials immutable to mitigate some kinds of supply-chain attacks.

refactor: use colors/safe

---

docs/config/02-files.md

Also added similar note for `dart` include type.
Fixes #3419

docs: mention that `html` include type does not work anymore

---

package-lock.json
package.json

As noted in [this issue](https://github.com/karma-runner/karma/issues/3562), `ua-parser-js` v0.7.21 has a [high severity issue](https://snyk.io/vuln/SNYK-JS-UAPARSERJS-610226).
This PR updates the dependency to correct the issue.

Update ua-parser-js dependency

---

client/karma.js
static/karma.js
test/client/karma.spec.js

Change the flag name to karmaNavigating and set it along all paths where
karma deliberately navigates. Other paths must be wrong.
Fixes #3560

fix(context): do not error when karma is navigating

---

package-lock.json
package.json

fix(cve): update ua-parser-js to 0.7.23 to fix CVE-2020-7793

---

lib/server.js
package-lock.json
package.json

BREAKING CHANGE:
Bump socket-io v2 to v3
Closes: #3569

feat: bump socket-io to v3 (wip)

---

docs/config/02-files.md
docs/dev/05-plugins.md
lib/middleware/karma.js
lib/server.js
lib/web-server.js
test/unit/middleware/karma.spec.js
test/unit/web-server.spec.js

As Dartium browser is no more, there are no browsers left, which support running Dart applications natively and therefore we can remove such support from Karma to reduce the maintenance effort.
BREAKING CHANGE: Using Karma to run Dart code in the browser is no longer supported. Use your favorite Dart-to-JS compiler instead.
`dart` file type has been removed without a replacement.
`customFileHandlers` DI token has been removed. Use [`middleware`](http://karma-runner.github.io/5.2/config/configuration-file.html#middleware) to achieve similar functionality.
`customScriptTypes` DI token has been removed. It had no effect, so no replacement is provided.

feat: remove support for running dart code in the browser

---

lib/cli.js
test/e2e/cli.feature
test/unit/cli.spec.js

This should make CLI more helpful as it will error out early and users can see that they have passed a wrong option instead of guessing why it does not have any effect.
Notes:
- unit tests use same parser configuration as production code (hence changes to tests)
- logic and test case for _ typos in option names was removed as this is covered by yargs strict mode now
- added documentation for couple of existing options as otherwise they are considered unknown and error out (but they do exist and were found in the unit tests)
BREAKING CHANGE: Karma is more strict and will error out if unknown option or argument is passed to CLI.

feat(cli): error out on unexpected options or parameters

---

client/karma.js
static/karma.js

The unload handler itself does not know about navigation.
May fix #3482

fix(client): do not reset karmaNavigating in onbeforeunload

---

lib/server.js

The v8 engine includes the error with the stack and most of the time we
need the stack also.

feat(server): print stack of unhandledrejections

---

lib/index.js
lib/server.js

BREAKING CHANGE: Deprecated `require('karma').server.start()` and `require('karma').Server.start()` variants were removed from the public API. Instead use canonical form:
```
const { Server } = require('karma');
const server = new Server();
server.start();
```

feat(server): remove deprecated static methods

---

docs/dev/02-making-changes.md
gruntfile.js
package-lock.json
package.json
scripts/client.js

Remove bundling logic from Grunt and introduce watch mode into the scripts/client.js. New script (`npm run build:watch`) allows to watch for the changes in client sources and bundle them automatically.
This also fixes a bug where `npm run build` could swallow errors and silently do nothing.
Fixes #3599

chore(build): unify client bundling scripts

---

client/karma.js
lib/server.js
static/karma.js
test/client/karma.spec.js

emit the `complete` event after the navigation events, if any.
The complete event on the client triggers the server to begin shutdown.
The shutdown can race with the navigate context.
Use navigateContetTo() for the returnUrl and fix up the test.

fix(test): clear up clearContext

---

client/karma.js
lib/browser.js
lib/server.js
static/karma.js
test/client/karma.spec.js
test/e2e/reconnecting.feature
test/e2e/support/reconnecting/test.js
test/unit/browser.spec.js
test/unit/server.spec.js

The reconnecting test is flakey, sometimes running the tests twice. This is exactly
the behavior we are trying to prevent. Hard to reproduce.

chore(test): mark all second connections reconnects

---

lib/server.js
test/unit/server.spec.js

The main change in behavior is the removal of `dieOnError` method. Previously Karma would send SIGINT to its own process and then trigger clean up logic upon receiving this signal. It is a pretty convoluted way to trigger shutdown. This commit extracts clean up logic into the `_close()` method and calls this method directly everywhere.
This change solves two issues:
- Makes life easier for other tools (like Angular CLI), which use Karma programmatically from another process and killing whole process on Karma error may not be the most convenient behavior. Instead Karma will clean up all its resources and notify caller using the `done` callback.
- Allows to remove last Grunt bits in the future PR. When running unit tests without Grunt wrapper the SIGINT is received by the Mocha process, …

fix(server): clean up close server logic

---

lib/middleware/karma.js
test/e2e/error.feature
test/e2e/support/error/import-something-from-somewhere.js

Fix #3572
Same as the fix by @jehon, but with a test.

fix(middleware): catch errors when loading a module

---

client/karma.js
client/main.js
client/updater.js
static/karma.js
test/client/karma.spec.js

The banner is visible in videos so we can have some client side
info on the state if it breaks.

feat(client): update banner with connection, test status, ping times

---

lib/server.js
lib/web-server.js
test/unit/web-server.spec.js

The removal of `customFileHandlers` turned out to be more disruptive change than anticipated as this provider is still used by several popular plugins: https://github.com/karma-runner/karma/issues/3619, https://github.com/ryanclark/karma-webpack/issues/462, https://github.com/angular/angular-cli/issues/19815. Hence we restore the provider and print a deprecation warning to make upgrading easier. This should give more time for the plugin authors to release new versions and users to adopt these versions.
How it looks now:

fix: restore `customFileHandlers` provider

---

lib/server.js

fix(server): set maxHttpBufferSize to the socket.io v2 default

---

client/karma.js
client/updater.js
static/karma.js

We use karma to run unit tests on browser and it crashes on IE11 & old Chrome because of invalid token (template literal in this case). This only happens on v6.x

fix: avoid ES6+ syntax in client scripts

---

docs/config/03-browsers.md

The Sauce Labs plugin link goes to a module at version 0.0.0 that hasn't been published in 5 years. Update the link to point to the module that is at version 3.4.3 and was published two months ago. In addition, this module is within the karmar-runner GitHub org.

Fix link to Sauce Labs plugin

---

test/unit/mocha-globals.js

Use https://log4js-node.github.io/log4js-node/recording.html to verify logs

chore(testing): stop log4js output in unit tests

---

package-lock.json
package.json
test/client/karma.conf.js
test/client/karma.spec.js

They were failing because of unsupported arrow function syntax in two places:
- in karma.spec.js file (only affecting Karma's own tests)
- in socket.io.js file installed from NPM, hence the dependency update (this affected Karma consumers)
Enabled BrowserStack tests on IE 11 to prevent regressions.

fix: ensure that Karma supports running tests on IE 11

---

lib/cli.js
test/e2e/cli.feature

As discussed in #3625 there are multiple cases, where Karma users rely on the possibility to pass arbitrary options/arguments to the karma CLI. These arguments are either handled in a `karma.conf.js` file or are consumed by Karma plugins. Given the disruptive effect of the strict parameters validation and the lack of the feasible workarounds, the feature is reverted until we have better understanding of the custom options/arguments use cases and can implement a solution which works for everybody.

fix(cli): temporarily disable strict parameters validation

---

client/karma.js
context/karma.js
static/context.js
static/karma.js
test/client/karma.spec.js

Previous code was susceptible to the race condition in Safari browser. Specifically below piece:
```
iframe.src = policy.createURL(url)
karmaNavigating = false
```
There is no guarantee that onbeforeunload event will be triggered synchronously after setting `iframe.src`. It was the case in Chrome and Firefox, but not in Safari, where this caused an error every test run. New approach resets the onbeforeunload handler before navigation is triggered by Karma itself to avoid the need for synchronization and this race condition altogether. The handler will be restored by the new context once it is loaded.
PS Code is a bit fragile as there is an implicit dependency on `onbeforeunload` from the context, but I can't think of a cleaner approach.

fix(client): fix a false positive page reload error in Safari

---

test/client/karma.conf.js
test/client/stringify.spec.js

In Safari stringified Proxy object has ProxyObject as a name, but in other browsers it does not.
Enabled Safari tests on BrowserStack to prevent future regressions.

chore(test): adjust test to pass in Safari browser

---

lib/launchers/process.js
test/unit/launchers/process.spec.js

This PR is to ensure the launcher process error is reported in the logs when the process exit event is not emitted which can happen in some cases.
As per described on this page https://nodejs.org/api/child_process.html#child_process_event_error, "The 'exit' event may or may not fire after an error has occurred. When listening to both the 'exit' and 'error' events, guard against accidentally invoking handler functions multiple times."
**Without this fix**, if the browser binary file is missing, Karma will report the following **if only in Debug mode**:
```
DEBUG [launcher]: Process {{browser_name}} exited with code -1
```
This is not really helpful to the users and if debug log level is not set, they won't see this message.
**With this fix**, if the browser binary file is missing, Karma …

Bug fix: Report launcher process error when the process exit event is not emitted

---

lib/config.js

Call require('ts-node').register() after checking configFilePath has `.ts` extension
Fixes #3329
сс @devoto13

fix(config): check extension before ts-node register

---

docs/config/01-configuration-file.md
docs/config/05-plugins.md
docs/dev/05-plugins.md
lib/config.js
lib/plugin.js

Changes:
- Promote `require('karma-plugin')` form over `'karma-plugin'` form. Former makes it more clear that plugin is imported from an NPM package and it is a regular JS object, there is no magic behind it. This is inspired by #3498 where user is not aware that it is even possible. This also should make it easier with plug'n'play package managers (like Yarn 2).
- Explain that `plugins` array does not activate plugins, but only registers them to clarify https://github.com/karma-runner/karma/issues/1247#issuecomment-312267740.
- Explain the plugin structure, DI and how to build a new plugin.
- Re-arrange "Developing plugins" page to make it easier to add more information about every plugin type. Adding actual information should be done in the separate PRs though.
Fixes #1247

docs(plugins): add more information about plugins

---

lib/middleware/karma.js
test/unit/middleware/karma.spec.js

fix: patch karma to allow loading virtual packages

---

.travis.yml

The rule between master and branch should be different to take the PR reference in consideration when merging.
---
This PR should be fixing the current build failure on master due to the latest commit message `fix: report launcher process error when exit event is not emitted (#3647)` being more than 72 characters (https://travis-ci.org/github/karma-runner/karma/jobs/757457475).
---
The problem is that the same `header-max-length` rule is applied to master and the PR branches and when a PR branch is merged the commit message has the PR reference appended to it making the length longer and potentially breaking the `commitlint` on master
Using different `header-max-length` rules for master and branches.
* `header-max-length` rule on master set to 80 characters to **temporary fix** the build …

fix(commitlint): skip task on master

---

lib/plugin.js

If you wish load all scoped package plugins by `@*/karma-*` like `karma-*`, karma doesn't handle it.
It'll be modified to `RegExp("^@.*/karma-*")` internally, and karma doesn't care scoped package's sub directories.
In this PR, add features below.
- support plugin name with multiple `*` (replace ALL `*` to `.*`)
- `@*/karma-*` is now valid
- `karma-*` also work same as before
- **however, if anyone already force using multiple `*` (such as `karma-*-foo-.*`), there is a risk of incompatibility**
- when finding plugin, get scoped package name now correctly (before: `@foo`, now: `@foo/bar`)
Fixes #3656

feat(plugins): add support wildcard config for scoped package plugin

---

test/unit/plugin.spec.js

Depends on and includes https://github.com/karma-runner/karma/pull/3659 (just want to run CI, for now, will rebase before the merge).

test(plugins): add missing tests for plugin resolution logic

---

docs/dev/04-public-api.md
lib/cli.js
lib/config.js
lib/runner.js
lib/server.js
lib/stopper.js
test/unit/cli.spec.js
test/unit/config.spec.js
test/unit/server.spec.js

With this change, Karma allows to return a `Promise` from a configuration function directly or make such function `async` and thus allows to perform some asynchronous initialization/fetch configuration from somewhere. When the configuration function returns a Promise, Karma will wait until the promise is resolved before it proceeds with the next steps.
Example usage:
```js
module.exports = async (config) => {
const karmaConfig = await getKarmaConfig("dev");
config.set({
...karmaConfig
});
};
```
For Karma's end-users the change is fully backward compatible. For Karma's programmatic users the change is backward compatible, but the current behavior of `parseConfig()`, `Server`, `runner`, and `stopper` is deprecated and will change in the next major release. New behavior (which supports …

feat: support asynchronous `config.set()` call in karma.conf.js

---

client/karma.js
static/karma.js

When useiframe false and clearContext true and IE11, the clearContext
blocks the complete event.

fix(client): clearContext after complete sent

---

static/client.html
static/client_with_context.html
test/client/karma.conf.js

So the symptom is that after Karma page is loaded in IE9 the tests don't run and Karma is stuck at the "starting" step. Reloading the page once or twice makes IE9 connect to the server and tests pass successfully.
After an "exciting" debugging session I figured out that the problem is that on the first load (and sometimes after the page reload) [`io` variable](https://github.com/karma-runner/karma/blob/026fff870913fb6cd2858dd962935dc74c92b725/client/main.js#L14), which should be set by the `socket.io.js` script is undefined. It looks like IE9 silently stops executing `socket.io.js` script somewhere midway and switches to the next script causing the `io` variable to be undefined. I assume it hits some limit or threshold or whatnot. Couldn't find much information on the Internet, besides …

fix: fix running tests in IE9

---

docs/config/04-preprocessors.md

Ported from https://github.com/karma-runner/karma-runner.github.com/pull/55
I chose to keep "If a file matches multiple keys, karma will do its best to execute the preprocessors in a reasonable order..." part as I believe it is still how it works and it is still relevant.

docs: add more information on `config.preprocessor_priority`

---

.travis.yml
appveyor.yml
docs/dev/02-making-changes.md
package-lock.json
package.json
test/client/karma.conf.js

This has the same result (symlink to the `karma` in the node_modules), but has two benefits:
- karma developers don't need to run extra command
- no peer dependency warnings when `npm install` is run

chore: replace `init` scripts with a dependency on itself

---

CHANGELOG.md
docs/about/03-migration.md
docs/dev/01-contributing.md
docs/dev/03-maintaining.md
docs/dev/04-public-api.md
docs/dev/05-plugins.md
docs/dev/06-git-commit-msg.md
docs/index.md
docs/intro/04-faq.md
docs/intro/05-troubleshooting.md
docs/plus/01-requirejs.md
docs/plus/02-travis.md
docs/plus/03-jenkins.md
docs/plus/04-semaphore.md
docs/plus/06-angularjs.md
docs/plus/08-emberjs.md
docs/plus/09-codio.md
docs/plus/10-teamcity.md

PR to switch to the new markdown renderer for the documentation website: https://github.com/karma-runner/karma-runner.github.com/pull/62.
Had to put metadata between --- --- (Jekyll syntax) as the previous syntax was not supported by the new Markdown parser. Also several small changes to the markdown syntax for the new Markdown parser (see commits for details).

docs: updates to the documentation to support new markdown renderer

---

lib/middleware/proxy.js
test/unit/middleware/proxy.spec.js

When using the proxy feature of Karma, the target value can include the [scheme](https://tools.ietf.org/html/std66#section-3.1). It was used to determine the `https` variable to be sent to the [`http-proxy`](https://www.npmjs.com/package/http-proxy) `.createProxyServer` method. However, it is now disregarded by that package. Therefore, this PR cleans it up.

fix(server): clean up vestigial code from proxy

---

lib/middleware/karma.js
static/client.html
static/debug.html
test/unit/middleware/karma.spec.js

Previously %X_UA_COMPATIBLE% marker was only replaced if it was located at the start of the line. The limitation looks pretty arbitrary and caused the marker not to be replaced in the custom debug.html file used by Angular CLI as the marker was not located at the start of the line (probably because the file was re-formatted). This commit changes the behavior to replace the marker anywhere within the file, not just at the start of the line and thus fixes the problem for Angular CLI and potentially other people using custom files.
Fixes #3711

fix(middleware): replace %X_UA_COMPATIBLE% marker anywhere in the file

---

commitlint.config.js
docs/dev/06-git-commit-msg.md
package-lock.json
package.json
release.config.js

The commit conventions enforced by commitlint (conventional) were different than the conventions used by the semantic-release (angular). In practice, is was never a problem as they are pretty similar, but it's better to be consistent anyways. Update the commit conventions documentation according to the change and also extend it with the information about which kind of release is triggered by which commit type. Add explicit configuration for release rules for semantic-release to the configuration file - rules are the same as before, but now it is easier to see what they actually are.

build: use matching commitlint config

---

docs/dev/02-making-changes.md
package-lock.json
package.json

Previously, we relied on husky package to set up the Git hooks to automatically lint code and check the commit message conventions. While it is a nice feature it causes extra delays on commit/push for more experienced contributors and we still get many PRs with incorrect commit messages from the first-time contributors. Given the above reasons remove the husky dependency, Git hooks and replace them with a script which can be used locally. Note that CI continues to validate the commit message conventions as before.
It's a bit tricky to define a sensible `--from` value for the `commit:check` script. Ideally, we would like to verify all commits between the `master` and the user's branch, but there are many cases where it would fail: user could have committed to master directly, user's branch …

build: remove husky and validation hooks

---

lib/reporter.js
test/unit/reporter.spec.js

For some projects, a preprocessor like TypeScript may run to downlevel
certain features to a lower ECMAScript target. e.g. a project may
consume Angular for example, which ships ES2020.
If TypeScript, ESBuild, Babel etc. is used to do this, they may inject
generated code which does not map to any original source. If any of
these helpers (the generated code) is then part of a stack trace, Karma
will incorrectly report an error for an unresolved source map position.
Generated code is valid within source maps and can be denoted as
mappings with a 1-variable-length mapping. See the source map spec:
https://sourcemaps.info/spec.html.
The warning for generated code is especially bad when the majority of
file paths, and the actually relevant-portions in the stack are
resolved properly. e.g. …

fix(reporter): do not print warning if stack trace contains generated code invocation

---

docs/config/01-configuration-file.md
lib/launchers/capture_timeout.js
test/e2e/timeout.feature

Fixes a grammar error in the log message when a browser does not capture in time.
Fixes #3716

style: fix grammar error in browser capture log message

---

client/karma.js
static/karma.js
test/e2e/restart-on-change.feature
test/e2e/step_definitions/core_steps.js

The problem was caused by a race condition in the client JS implementation. When the `restartOnFileChange` option is enabled, the server would send [two commands](https://github.com/karma-runner/karma/blob/b153355de7e05559d877a625c9b0c5d23a3548bd/lib/server.js#L377) to the browser: `stop` and `execute`. Both of these commands navigate the context. `stop` navigates to the blank page, while `execute` navigate to the `context.html` thus triggering a test run. The `execute` command would trigger the navigation synchronously, but the `stop` command would trigger it on the next event loop tick. As a result, if both commands arrive almost at the same time, their order is effectively reversed: first schedule new execution and then immediately stop it. The bug is resolved by handling both commands …

fix: restartOnFileChange option not restarting the test run

---

lib/server.js
test/e2e/browser_console.feature

create folder path if it does not exist

---

test/e2e/cli.feature

\d no longer matches since 6.3.10 because of two-digit number.

test: fix version regex in the CLI test case

---

package-lock.json
package.json

Another one, hopefully contains all required changes :weary:
Pin `colors` package to `1.4.0` version due to security vulnerability. See details:
- [1.4.0...1.4.2 diff](https://diff.intrinsic.com/colors/1.4.0/1.4.2)
- https://github.com/Marak/colors.js/issues/285
- https://www.theverge.com/2022/1/9/22874949/developer-corrupts-open-source-libraries-projects-affected
- https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/

fix(deps): pin colors package to 1.4.0 due to security vulnerability

---

lib/constants.js

Closes: #3749
A simple fix to resolve the issue that was introduced from this change in Loj4js https://github.com/log4js-node/log4js-node/commit/3226b3de40da493c3a034ffa7694caa2aab1ef38#diff-ade4a5a1a21fa05e981597abfd6195ecf9459cc7681f8cbf873308ec0b0c4637

fix: update constants to remove deprecation warning from log4js

---

client/karma.js
static/karma.js

The `returnUrl` query parameter can be used to execute malicious code. For
example, visiting
`http://localhost:9876/?return_url=javascript:alert(document.domain)` will
display an alert.

fix(security): remove XSS vulnerability in `returnUrl` query param

---

lib/server.js

Setting `singleRun` and `autoWatch` to `false` will make the server remain idle
even when capturing a browser. It is a no-op combination. If it is detected,
fail and explain.

fix: warn when `singleRun` and `autoWatch` are `false`

---

.github/workflows/test.yml
test/client/karma.conf.js

BrowserStack can be flaky when there are multiple concurrent jobs running on
it. This commit makes sure that only 1 browser can run concurrently during the
`npm run test:client` jobs and that the "Test" GitHub Action workflow is only
trigerred once when creating a PR; having the `on: push` configuration made it
so that GH triggers two duplicate jobs when a PR is opened.

chore: prevent duplicate CI tasks on creating a PR

---

lib/reporters/base_color.js
package-lock.json
package.json

Per https://github.com/Marak/colors.js/issues/340, the colors package on which `karma` depends has been migrated to @colors/colors. This PR performs the (very simple) migration. Thanks for your help with getting this into the next release, and let me know if you need any help with getting this fix out or other maintenance tasks.

Update colors to maintained version

---

client/main.js
common/util.js
lib/completion.js
lib/events.js
lib/file.js
lib/helper.js
lib/launcher.js
lib/launchers/process.js
lib/middleware/karma.js
lib/runner.js
lib/url.js
static/context.js
static/karma.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated. While [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) isn't deprecated I replaced it with `slice()` as well.  `slice()` is generally a bit faster (and uses less bites as the name is shorter) and this way we don't have 2 functions which nearly do the same thing in the code.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

refactor: replace deprecated String.prototype.substr()

---

docs/config/01-configuration-file.md

See https://github.com/karma-runner/karma/pull/3660

docs(configuration-file): document async function

---

package-lock.json
package.json

This upgrades engine.io which has a uncaught exception issue: https://nvd.nist.gov/vuln/detail/CVE-2022-21676

Upgrade socket.io to v4.4.1

---

.github/workflows/lint.yml
.github/workflows/test.yml

Source of inspiration: https://github.com/karma-runner/karma-jasmine/pull/313

ci: lint and commitlint in its own workflow

---

client/karma.js
static/karma.js

Safari in iOS fails opening a new tab with the `window.open` API. This makes it explicit that that is the culprit, in the right case. Also, it suggests a workaround: enabling pop ups.

fix(client): error out when opening a new tab fails

---

.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
docs/intro/01-installation.md
docs/intro/04-faq.md
lib/middleware/proxy.js
lib/runner.js
lib/stopper.js
lib/utils/dns-utils.js
test/e2e/support/proxy.js

build: add Node 16 and 18 to the CI matrix
Update documentation, so that it does not become outdated whenever a new version of Node is released.
Test on the current version of Node, so we can spot problems early, but don't claim to support it as current release line sometimes introduces bugs, which are later fixed by Node itself.
Fixes #3728
---
fix: prefer IPv4 addresses when resolving domains
Node 17+ changed the DNS resolution (see https://github.com/nodejs/node/issues/40702), so now it resolves `localhost` according to the OS settings instead of IPv4-address first. The Karma server only listens on IPv4 address (127.0.0.1) by default, but the requests are sent to `localhost` in several places and `localhost` is resolved into IPv6 address (`::`) in Node 17+. So the run/stop/proxy …

Add support for Node.js 16 & 18

---

context/main.js
docs/dev/04-public-api.md
static/context.js

There are small typos in:
- context/main.js
- docs/dev/04-public-api.md
- static/context.js
Fixes:
- Should read `permission` rather than `permisison`.
- Should read `asynchronous` rather than `aynchronous`.

docs: Fix a few typos

---

package-lock.json
package.json

A specially crafted Sokcet.IO packet can trigger an uncaught exception on Sokcet.IO Server , thus killing the Node.js process. 
Refer CWE-754 : https://cwe.mitre.org/data/definitions/754.html , CWE-20 : https://cwe.mitre.org/data/definitions/20.html , CVE-2023-32695 : https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-32695 )
Similarly, a specially crafted HTTP request can trigger an uncaught exception on the Engine.IO server, thus killing the Node.js process. (Refer CWE-248 : https://cwe.mitre.org/data/definitions/248.html, CVE-2023-31125 : https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-31125)
These are potential security risks which are introduced by using socket.io@4..4.1 and need to be addressed in order to maintain the security of applications using karma.

Updated socket.io version to fix security issues with socket.io-parser and engine.io
