karma-runner/karma

- package.json
iojs just released 2.0 yesterday
> update engine field because iojs 2.0

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
I think every big open source project should have it.
> chore: Add code of conduct

- docs/config/02-files.md
I created this because of a discussion on Gitter I had with @maksimr 
I ran into this documentation, it left me confused and so I debugged an otherwise simple problem. I tried to be more specific to prevent this from happening to others in the future.
> Make loading assets more understandable

- lib/launchers/capture_timeout.js
- lib/middleware/karma.js
- lib/middleware/proxy.js
- lib/middleware/runner.js
- lib/middleware/source_files.js
- lib/web-server.js
- wallaby.js
Thanks @ArtemGovorov for setting up [wallaby](http://wallabyjs.com) in karma.
> chore: support wallabyjs for karma tests

- docs/plus/01-requirejs.md
Include information about the files property and how to get scripts loaded before requirejs.
Also update test-main.js extract to match template.
This requires https://github.com/karma-runner/karma/pull/1458
to be pulled first.
> Update requirejs information

- docs/about/01-versioning.md
- lib/launchers/process.js
- lib/temp_dir.js
- package.json
> Remove 0.8 cruft

- docs/config/02-files.md
@Dignifiedquire 
Pull request for karma-runner/karma#1445
> Updated example to have comment about libraries

- gruntfile.js
Only make the latest github release.
Push commits and tags in the workflow.
> chore(build): make release work properly

- lib/file-list.js
- test/e2e/steps/core_steps.coffee
- test/unit/file-list.spec.js
> fix(file-list): Ensure autowatchDelay is working.

- lib/file-list.js
- test/unit/file-list.spec.js
> fix(file-list): Use modified throttle instead of debounce

- client/karma.js
Change indentation to pass updated eslint
> style(client/karma): Fix indentation

- lib/reporter.js
- package.json
Reverts karma-runner/karma#1618
> revert(reporter): Replace memoizee library with a trivial solution

- lib/browser.js
- lib/launchers/process.js
- lib/logger.js
- lib/middleware/strip_host.js
Small typos I encountered while checking the code. Hope it helps :)
> style: small spelling fix

- docs/dev/04-public-api.md
Fixed small typos, nothing to be worried about. :smile:
> fix(docs): fix typos

- static/context.html
Updated comment wording that confused me a bit while reading through code.
> style(static/context.html): update comment wording

- docs/plus/02-travis.md
**package scripts**:
```
./node_modules/karma/bin/karma start --single-run --browsers PhantomJS ->
karma start --single-run --browsers PhantomJS`
```
**node**:
`0.10` -> `4`
> travis: simplified test script, updated node version

- lib/preprocessor.js
> fix(preprocessor): Improve handling of failed preprocessors

- lib/cli.js
- lib/completion.js
- lib/constants.js
- lib/file-list.js
- lib/helper.js
- lib/init/formatters.js
- lib/plugin.js
- lib/temp_dir.js
- lib/web-server.js
- package.json
- test/unit/file-list.spec.js
- test/unit/helper.spec.js
- test/unit/web-server.spec.js
Took the liberty to provide a fix here. I'm still hitting EMFILE in certain situations. Could it be due to launchers? I can definitely run my tests with a much lower ulimit -n now though.
Partially fixes #544
> fix: Switch all requires from fs to graceful-fs

- docs/dev/02-making-changes.md
The dev instructions miss few steps making it harder to get started with contributions
Fixes #1817
> docs: Update install-for-development instructions.

- docs/intro/01-installation.md
According to the FAQ, this works with Node.js 5.x.
> docs: Update 01-installation.md

- client/updater.js
Change 'ms' to 'seconds' in **updater.js**.
Closes *[#1936](https://github.com/karma-runner/karma/issues/1936)*
> fix(updater): Fix time unit on screen display from 'ms' to 'seconds'.

- docs/about/03-migration.md
- docs/config/01-configuration-file.md
- docs/config/02-files.md
- docs/config/03-browsers.md
- docs/config/04-preprocessors.md
- docs/dev/01-contributing.md
- docs/dev/02-making-changes.md
- docs/dev/03-maintaining.md
- docs/dev/04-public-api.md
- docs/dev/05-plugins.md
- docs/dev/06-git-commit-msg.md
- docs/intro/02-configuration.md
- docs/intro/03-how-it-works.md
- docs/intro/04-faq.md
- docs/intro/05-troubleshooting.md
- docs/plus/01-requirejs.md
- docs/plus/02-travis.md
- docs/plus/04-semaphore.md
- docs/plus/05-cloud9.md
- docs/plus/09-codio.md
- docs/plus/10-teamcity.md
Fix grammar in the documentation files.
> fix(docs): Fix grammar overall

- gruntfile.js
- lib/launcher.js
- package.json
- test/e2e/load.feature
- test/e2e/support/env.js
- test/unit/launcher.spec.js
> fix(launcher): Allow dynamic browser launches

- lib/middleware/proxy.js
- test/unit/middleware/proxy.spec.js
Derive port from proxy-protocol if present.
Closes #1987
> fix(proxy): Port mixup and infinite loop

- lib/reporter.js
- test/unit/reporter.spec.js
> fix(reporter): Better handling of non string error

- docs/config/01-configuration-file.md
- lib/config.js
- lib/launcher.js
- lib/reporters/base.js
- lib/server.js
- test/e2e/browser_console.feature
- test/e2e/steps/core_steps.js
- test/e2e/support/browser-console/log.js
- test/e2e/support/browser-console/test.js
- test/unit/reporters/base.spec.js
Implement `console.log` logging.
Closes #480
> Feature issue 480

- LICENSE
> chore(license): update year

- lib/launcher.js
> fix(launcher): Extra concurrent browser on launcher restart

- docs/config/01-configuration-file.md
- lib/web-server.js
- package.json
- test/unit/web-server.spec.js
allow setting an external module for use by KarmaServer
Closes #2424
> feat(web-server): allow overriding of default http module

- docs/config/03-browsers.md
docs: Correct grammar, punctuation, add link
Rewrote some sentences to make the 'flow' better.  Added a link to text 'Configuration File'.
> docs: Correct grammar, punctuation, add link

- docs/dev/04-public-api.md
- lib/index.js
- Export constants for public usage
This should implement #2361.
> feat(constants): export constants

- package.json
- test/unit/file-list.spec.js
- Upgrade mocha to v3
The test change is due to this behavior in Mocha: https://github.com/mochajs/mocha/issues/2407
> chore(mocha): upgrade to v3

- lib/reporters/progress.js
- test/unit/reporters/progress.spec.js
> fix(reporters:progress):  Cannot read property map of undefined

- lib/reporter.js
- test/unit/reporter.spec.js
- Strip only specified hostname & port from result
This should fix #2209
> fix(reporter): strip only hostname/port

- docs/config/01-configuration-file.md
Documentation for processKillTimeoutProperty
Closes #2447
> docs(runner): Document processKillTimeout property

- .babelrc
> chore: ensure test failures show correct line number

- test/unit/file-list.spec.js
@see https://travis-ci.org/karma-runner/karma/jobs/213063485#L2154
Unhandled rejection Error: "file_list_modified" was not emitted
at
/home/travis/build/karma-runner/karma/test/unit/file-list.spec.js:812:17
> chore: Remove unhandled rejection Error from unit tests

- .travis.yml
> chore(travis): only update npm in Node<5 and only to npm@3

- .travis.yml
- appveyor.yml
- Remove active testing of node versions below 4
> feat(ci): disable testing of node versions below 4

- lib/config.js
- Remove polling usage for file change watching with chokidar on Mac OS
Closes #2669
> feat(config): remove polling usage

- .mailmap
In this way my past contributions are mapped correctly.
> chore: update @mgol's name in .mailmap

- config.tpl.coffee
- config.tpl.js
- config.tpl.ls
- config.tpl.ts
Comments in template files did not reflect all options as described in docs, so changed them to reflect actual state.
> Fixed config.tpl.* comments

- lib/launcher.js
> feat: trim whitespace in browser name

- docs/config/01-configuration-file.md
> Document port collision scenario

- package.json
Fix AppVeyor build by select specific version of `useragent` in `package.json`
> fix(common): fix AppVeyor build

- common/stringify.js
- test/client/stringify.spec.js
This closes #2854 and closes #2863
> fix(common): show more detailed info about error logged in console

- docs/config/01-configuration-file.md
See: https://github.com/karma-runner/karma-chrome-launcher/pull/111#issuecomment-298700314.
> Documentation update: add "ChromeHeadless" to list of possible browsers

- config.tpl.coffee
- config.tpl.js
- config.tpl.ls
- config.tpl.ts
- lib/init/formatters.js
- lib/utils/file-utils.js
- test/unit/init/formatters.spec.js
Refactor `lib/init/formatters` to use ES6
> refactor(formatters): refactor formatters.js

- docs/config/02-files.md
Also trying to increase the discoverability of the custom middleware feature.
> docs(Files): minor content updates

- lib/init.js
- lib/init/log-queue.js
- lib/init/state_machine.js
Within this pull request I updated `karma init` and `state_machine` to ES6. 
I've also created `log-queue.js` file which purpose is to store logs from `npm install`
> refactor(init): refactor karma init

- package.json
- wallaby.js
This change was originally added by @dignifiedquire, but mixed with other changes.
> fix(deps): remove babel-core and babel call in wallaby.

- docs/dev/04-public-api.md
extract config to a var to create better clarity for API usage
> docs: better clarity for API usage

- .travis.yml
- appveyor.yml
- package.json
> chore: remove support for node 4, update log4js

- .travis.yml
Also add some debug messages for commits and remove an old node4 command.
> fix(travis): Validate TRAVIS_PULL_REQUEST_SHA rather than TRAVIS_COMMIT.

- client/main.js
- lib/browser.js
Log something on all disconnect() calls.
Up the timeout as suggested by ndcornelius@ on #3102
> fix(travis): Up the socket timeout 2->20s.

- lib/middleware/common.js
- package.json
- test/unit/web-server.spec.js
This is the similar to @dignifiedrequire #2997 first commit
> chore(deps): update mime -> 2.3.1

- lib/browser_collection.js
- lib/cli.js
- lib/server.js
- test/unit/browser_collection.spec.js
> fix(runner): Make exit code configurable when tests are failing

- LICENSE
> chore(license): change year to 2018

- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md
- docs/intro/01-installation.md
- docs/intro/04-faq.md
And fixed two links pointing to specific versions of documentation.
> Updated supported Node versions in the documentation

- lib/launchers/retry.js
> refactor(launcher): use this instead self in retry launcher

- lib/middleware/karma.js
> refactor(middleware): get rid of util.format

- lib/cli.js
- lib/completion.js
- lib/config.js
- lib/launcher.js
- lib/launchers/process.js
- lib/middleware/karma.js
- lib/middleware/proxy.js
- lib/plugin.js
- lib/preprocessor.js
- lib/reporter.js
> refactor(server): use includes/startsWith methods instead indexOf

- package.json
- test/unit/file-list.spec.js
- test/unit/launchers/base.spec.js
- test/unit/launchers/capture_timeout.spec.js
- test/unit/launchers/process.spec.js
- test/unit/launchers/retry.spec.js
- test/unit/middleware/karma.spec.js
- test/unit/middleware/source_files.spec.js
- test/unit/mocha-globals.js
- test/unit/reporter.spec.js
- test/unit/utils/bundle-utils.spec.js
Based on migration guides https://sinonjs.org/releases/v6.1.5/
> chore(deps): update sinon 3.x->6.x

- lib/completion.js
> refactor(completion): small refactoring of lib/completion

- lib/config.js
- test/unit/config.spec.js
> refactor(config): small refactoring of lib/config

- lib/browser_collection.js
- lib/executor.js
- test/unit/browser_collection.spec.js
- getNonReady method added into BrowserCollection
> refactor(server): refactoring of executor and browser_collection

- lib/middleware/proxy.js
> refactor(server): refactoring of proxy

- lib/server.js
- lib/utils/net-utils.js
> refactor(server): Clearer error messages on fatal errors

- package.json
> fix(deps): upgrade sinon-chai 2.x -> 3.x

- CHANGELOG.md
Fixes https://github.com/karma-runner/karma/issues/3213
> fix(changelog): remove release which does not exist

- lib/file-list.js
> refactor(fileList): small refactoring

- LICENSE
Signed-off-by: Atul Bhosale <atul1bhosale@gmail.com>
> chore(license): Update copyright notice to 2019 [ci skip]

- package.json
- yarn.lock
> chore: upgrade log4js to v4.0.0

- lib/middleware/karma.js
> fix(middleware): log invalid filetype

- lib/server.js
- test/unit/server.spec.js
> fix(server): Add error handler for webserver socket.

- package.json
> fix(deps): lodash update.

- lib/config.js
- test/unit/config.spec.js
> fix(config): Simplify error processing.

- .travis.yml
xvfb config depends on ubuntu version.
> fix(travis): Pin to trusty

- appveyor.yml
This config is supposed to send notifications back to github...
> chore(appveyor): Notification config.

- docs/config/01-configuration-file.md
Add failOnFailingTestSuite to docs
> docs(commit-msg): Add failOnFailingTestSuite option to docs

- package.json
See https://github.com/karma-runner/karma-browserstack-launcher/issues/152
Maybe the cause of our travis fails.
> fix(deps): back to karma-browserstack-launcher 1.4

- commitlint.config.js
- package-lock.json
- package.json
This config ensure that commit messages will match the syntax required for semantic-release
> chore(lint): add commitlint, husky trigger, and config.

- .travis.yml
- release.config.js
> chore(travis): Activate semantic-release on node-12 test success

- lib/middleware/common.js
BREAKING CHANGES: Removed PromiseContainer class as not used
> refactor(server): remove PromiseContainer class 

- .travis.yml
Use the travis web UI to set values in future
> chore(ci): remove secure encryption var

- .travis.yml
See: https://docs.travis-ci.com/user/sauce-connect/
> chore(ci): use travis UI for sauce config

- docs/dev/02-making-changes.md
- test/client/karma.conf.js
Use NPM scripts instead of shell commands and Grunt.
> docs: simplify repository setup steps

- test/e2e/step_definitions/core_steps.js
- test/e2e/step_definitions/hooks.js
- test/e2e/support/env.js
- test/e2e/support/world.js
See cucumber [changelog](https://github.com/cucumber/cucumber-js/blob/7d0a1f7c85478dddbdcadf9489b8890db77be3a2/CHANGELOG.md#deprecations). Despite huge diff there are no code changes besides indentation in this commit.
> chore(test): remove usage of deprecated defineSupportCode

- package-lock.json
- package.json
No breaking changes affecting Karma as far as I can tell from the changelog.
> fix(dependencies): update to latest log4js major

- package-lock.json
- package.json
> fix(dependencies): update to safe version of http-proxy

- appveyor.yml
As per https://github.com/appveyor/ci/issues/3502.
> chore: fix appveyor glitch on Node 14

- package-lock.json
- package.json
As it contains a breaking change per #3557.
> fix: revert source-map update

- package-lock.json
- package.json
Fixes: [#3577](https://github.com/karma-runner/karma/issues/3577)
> fix(cve): update yargs to 16.1.1 to fix cve-2020-7774 in y18n

- docs/config/02-files.md
> docs: document how to load files from another server

- SECURITY.md
> docs: create security.md

- package-lock.json
- package.json
> fix(deps): bump log4js to resolve security issue

- client/karma.js
- static/karma.js
> fix: remove string template from client code

- docs/config/02-files.md
- lib/config.js
- lib/file-list.js
- lib/file.js
- lib/middleware/karma.js
- lib/url.js
- test/unit/middleware/karma.spec.js
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
> Support subresource integrity verification

- docs/config/02-files.md
- lib/config.js
- test/unit/config.spec.js
> fix: pass integrity value
